export const SECOND = 1000;
export const MINUTE = 60 * SECOND;
export const HALF_HOUR = 30 * MINUTE;
export const HOUR = 2 * HALF_HOUR;

export const ERROR_HANDLER_TYPE_ALERT = "ERROR_HANDLER_TYPE_ALERT";
export const ERROR_HANDLER_TYPE_LOCAL = "ERROR_HANDLER_TYPE_LOCAL";

export const SUCCESS_HANDLER_TYPE_ALERT = "SUCCESS_HANDLER_TYPE_ALERT";
export const SUCCESS_HANDLER_TYPE_LOCAL = "SUCCESS_HANDLER_TYPE_LOCAL";
