ARG BUILDTAG=build
FROM diproxy:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY diproxy/tests ./tests
