ARG BUILDTAG=build
FROM keeper:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

COPY keeper/test-requirements.txt ./
COPY keeper/.pylintrc keeper/.noserc keeper/.coveragerc ./

COPY optscale_client/report_client optscale_client/report_client

RUN pip install --no-cache-dir -r test-requirements.txt


COPY keeper/report_server/tests keeper/report_server/tests
