ARG BUILDTAG=build
FROM keeper:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY report_server/tests ./tests
