import auth.auth_server.handlers.v1.action_resources
import auth.auth_server.handlers.v1.actions
import auth.auth_server.handlers.v1.assignments
import auth.auth_server.handlers.v1.authorization
import auth.auth_server.handlers.v1.authorization_userlist
import auth.auth_server.handlers.v1.digests
import auth.auth_server.handlers.v1.roles
import auth.auth_server.handlers.v1.scopes
import auth.auth_server.handlers.v1.tokens
import auth.auth_server.handlers.v1.types
import auth.auth_server.handlers.v1.users
