# pylint: disable=C0103
"""verification_codes

Revision ID: 245d4295bbd6
Revises: 0321f4e3fe3f
Create Date: 2024-08-21 13:48:45.605522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '245d4295bbd6'
down_revision = '0321f4e3fe3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'verification_code',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('valid_until', sa.TIMESTAMP(), nullable=False),
        sa.Column('code', sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_code_email'),
                    'verification_code', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_code_email'),
                  table_name='verification_code')
    op.drop_table('verification_code')
    # ### end Alembic commands ###
