""""removed_user_name"

Revision ID: 3481a6b2731b
Revises: 19a8c2c4383b
Create Date: 2017-05-22 09:38:21.510903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String


# revision identifiers, used by Alembic.
revision = '3481a6b2731b'
down_revision = '19a8c2c4383b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_name', table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=256),
                                    nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    user_table = table('user',
                       column('email', String(256)),
                       column('name', String(256)))

    update_name = update(user_table).values(name=user_table.c.email)
    try:
        session.execute(update_name)
        session.commit()
    finally:
        session.close()

    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    # ### end Alembic commands ###
