""""added_user_is_password_autogenerated"

Revision ID: 716f4735a9ea
Revises: 69b97ccc8ec3
Create Date: 2021-09-20 18:17:13.464820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716f4735a9ea'
down_revision = '69b97ccc8ec3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_password_autogenerated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_password_autogenerated')
    # ### end Alembic commands ###
