""""add_shared_roles"

Revision ID: 798a1c677131
Revises: bc4f75f1c8bd
Create Date: 2017-06-09 15:34:48.919359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798a1c677131'
down_revision = 'bc4f75f1c8bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('shared', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'shared')
    # ### end Alembic commands ###
