""""fix_username_unique"

Revision ID: b743d2ee7700
Revises: 2b5e2351dc6a
Create Date: 2017-07-18 12:18:30.766478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b743d2ee7700'
down_revision = '2b5e2351dc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_email_unique', 'user', ['email', 'deleted_at'],
                    unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index('idx_user_email_unique', table_name='user')
    # ### end Alembic commands ###
