ARG BUILDTAG=build
FROM jira_bus:${BUILDTAG}

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
COPY jira_bus_server/tests jira_bus_server/tests
RUN pip install --no-cache-dir -r test-requirements.txt
