""""delete_in_use_schedules"

Revision ID: 003afab1a585
Revises: d5ad8aa61f68
Create Date: 2020-06-18 10:35:09.742281

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '003afab1a585'
down_revision = 'd5ad8aa61f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'schedule_id',
               existing_type=sa.String(length=36),
               nullable=True)
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_1', 'task', 'schedule', ['schedule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_ibfk_1', 'task', type_='foreignkey')
    op.create_foreign_key('task_ibfk_1', 'task', 'schedule', ['schedule_id'], ['id'])
    op.alter_column('task', 'schedule_id',
               existing_type=sa.String(length=36),
               nullable=False)
    # ### end Alembic commands ###
