""""removed_report_template_column"

Revision ID: b4443e4dd1ed
Revises: 6556e12c599c
Create Date: 2020-07-07 07:32:09.877548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import String


# revision identifiers, used by Alembic.
revision = "b4443e4dd1ed"
down_revision = "6556e12c599c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("report", "template")
    # ### end Alembic commands ###


def downgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    op.add_column(
        "report", sa.Column("template", sa.String(length=128), nullable=False)
    )

    report_table = table(
        "report",
        column("module_name", String(128)),
        column("template", String(128)),
    )
    try:
        session.execute(
            report_table.update().values(template=report_table.c.module_name)
        )
        session.commit()
    finally:
        session.close()
