""""added_task_parent_id"

Revision ID: d777a3b2707c
Revises: a3f9fa01a7f6
Create Date: 2020-06-26 05:06:26.216187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d777a3b2707c"
down_revision = "a3f9fa01a7f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("parent_id", sa.String(length=36),
                                    nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "parent_id")
    # ### end Alembic commands ###
