""""recipient_uc_with_user_id"

Revision ID: f45ed78f1de9
Revises: 0e2ab5729d0e
Create Date: 2020-07-07 09:02:04.345806

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "f45ed78f1de9"
down_revision = "0e2ab5729d0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uc_recipient_role_purpose_scope_user", "recipient", type_="unique"
    )
    op.create_unique_constraint(
        "uc_recipient_role_purpose_scope_user",
        "recipient",
        ["role_purpose", "scope_id", "user_id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uc_recipient_role_purpose_scope_user", "recipient", type_="unique"
    )
    op.create_unique_constraint(
        "uc_recipient_role_purpose_scope_user",
        "recipient",
        ["role_purpose", "scope_id"],
    )
    # ### end Alembic commands ###
