ARG BUILDTAG=build
FROM restapi:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY rest_api_server/tests ./tests
COPY run_tests.py ./
COPY prepare_clickhouse_local.sh ./
