""""resource_meta"

Revision ID: 01a187c9482f
Revises: 865bb21cc4a4
Create Date: 2020-09-22 09:30:05.954973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a187c9482f'
down_revision = '3a35cbdb4fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('meta', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'meta')
    # ### end Alembic commands ###
