""""add_cloud_type_column_to_cloudsite"

Revision ID: 04e6e0e8e763
Revises: 56ad3e62d082
Create Date: 2018-06-21 07:16:41.941371

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision = '04e6e0e8e763'
down_revision = '56ad3e62d082'
branch_labels = None
depends_on = None
cloud_types = sa.Enum('OPENSTACK', 'OPENSTACK_CNR', 'FAKE', 'AWS_CNR')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsite', sa.Column('cloud_type', cloud_types, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloudsite', 'cloud_type')
    # ### end Alembic commands ###
