""""cloud_site_states"

Revision ID: 12015f05eab7
Revises: 541673c481bd
Create Date: 2017-07-18 15:23:34.041581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

revision = '12015f05eab7'
down_revision = 'c3c4691bec55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    cs_table = sa.table('cloudsite', sa.Column('state', sa.String(256)),
                        sa.Column('deleted_at', sa.Integer()))
    try:
        update_running = sa.update(cs_table).values(state='RUNNING').where(
            cs_table.c.deleted_at == 0)
        session.execute(update_running)

        update_other = sa.update(cs_table).values(state='PENDING').where(
            cs_table.c.deleted_at != 0)
        session.execute(update_other)
        session.commit()
    finally:
        session.close()

    op.alter_column('cloudsite',
                    'state',
                    type_=sa.Enum('PENDING', 'CREATING', 'UPDATING',
                                  'DELETING', 'RUNNING', 'ROLLING_BACK',
                                  'ERROR', name='cloudsitestates'),
                    existing_type=sa.String(length=256),
                    server_default='PENDING',
                    nullable=False)
    op.add_column(
        'cloudsite', sa.Column('error_cause', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cloudsite',
                    'state',
                    existing_type=sa.Enum('PENDING', 'CREATING', 'UPDATING',
                                          'DELETING', 'RUNNING', 'ROLLING_BACK',
                                          'ERROR', name='cloudsitestates'),
                    type_=sa.String(length=256),
                    nullable=True)
    op.drop_column('cloudsite', 'error_cause')
    # ### end Alembic commands ###
