""""update_ttl_for_invites"

Revision ID: 1c36f18f71c7
Revises: 5d5b4d5d032b
Create Date: 2020-06-02 02:41:31.498130

"""
from alembic import op
import datetime
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String, select


# revision identifiers, used by Alembic.
revision = '1c36f18f71c7'
down_revision = '5d5b4d5d032b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        invitation_table = table('invite', column('created_at', sa.TIMESTAMP()),
                               column('ttl', sa.Integer()), column('id', String(36)))
        stmt = select([invitation_table]).where(invitation_table.c.ttl == 0)
        invites = session.execute(stmt)
        for i, invite in enumerate(invites):
            created_at = int(invite.created_at.replace(
                tzinfo=datetime.timezone.utc).timestamp())
            ttl = created_at + int(datetime.timedelta(days=30).total_seconds())
            stmt = update(invitation_table).values(ttl=ttl).where(
                invite['id'] == invitation_table.c.id)
            session.execute(stmt)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###