""""retention_table"

Revision ID: 2027610f7083
Revises: 61039ec12750
Create Date: 2017-04-07 02:40:05.536198

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, String, insert

# revision identifiers, used by Alembic.
revision = '2027610f7083'
down_revision = '99f16ba3b402'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retention',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('daily', sa.Integer(), nullable=False),
    sa.Column('weekly', sa.Integer(), nullable=False),
    sa.Column('monthly', sa.Integer(), nullable=False),
    sa.Column('annually', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###

    retention_table = table('retention',
                            column('owner_id', String(36)),
                            column('interval', Integer),
                            column('daily', Integer),
                            column('weekly', Integer),
                            column('monthly', Integer),
                            column('annually', Integer))
    ins_stmt = insert(retention_table).values(
        owner_id=None,
        interval=7,
        daily=14,
        weekly=4,
        monthly=6,
        annually=2)
    session.execute(ins_stmt)
    session.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retention')
    # ### end Alembic commands ###
