""""cs_detached_deleted_states"

Revision ID: 2064620faa49
Revises: 5731fca8c174
Create Date: 2018-07-10 15:28:49.719690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2064620faa49'
down_revision = '5731fca8c174'
branch_labels = None
depends_on = None
old_cs_states = sa.Enum('PENDING', 'CREATING', 'UPDATING', 'DELETING',
                        'DETACHING', 'RUNNING', 'ROLLING_BACK', 'ERROR')
new_cs_states = sa.Enum('PENDING', 'CREATING', 'UPDATING', 'DELETING',
                        'DETACHING', 'DELETED', 'DETACHED', 'RUNNING',
                        'ROLLING_BACK', 'ERROR')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cloudsite', 'state', existing_type=new_cs_states, nullable=True,
        existing_server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ct = sa.sql.table('cloudsite', sa.sql.column('state', new_cs_states))
    op.execute(ct.update().where(ct.c.state.in_(
        ['DETACHED', 'DELETED'])).values(state='ERROR'))
    op.alter_column(
        'cloudsite', 'state', existing_type=old_cs_states, nullable=True,
        existing_server_default=sa.text("'PENDING'"))
    # ### end Alembic commands ###
