""""2.5 cloudcredentials to cloudaccount"

Revision ID: 2684a850a5fe
Revises: 2b975c5dc25b
Create Date: 2020-09-07 11:58:59.724183

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '2684a850a5fe'
down_revision = '2b975c5dc25b'
branch_labels = None
depends_on = None

old_name = "cloudcredentials"
new_name = "cloudaccount"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reportimport_ibfk_1', 'reportimport', type_='foreignkey')
    op.drop_constraint('resource_ibfk_2', 'resource', type_='foreignkey')
    op.rename_table(old_name, new_name)
    op.create_foreign_key("reportimport_ca_fk", 'reportimport', 'cloudaccount', ['cloud_credentials_id'], ['id'])
    op.create_foreign_key("resource_ca_fk", 'resource', 'cloudaccount', ['cloud_credentials_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("resource_ca_fk", 'resource', type_='foreignkey')
    op.drop_constraint("reportimport_ca_fk", 'reportimport', type_='foreignkey')
    op.rename_table(new_name, old_name)
    op.create_foreign_key('resource_ibfk_2', 'resource', 'cloudcredentials', ['cloud_credentials_id'], ['id'])
    op.create_foreign_key('reportimport_ibfk_1', 'reportimport', 'cloudcredentials', ['cloud_credentials_id'], ['id'])
    # ### end Alembic commands ###
