""""removed_empty_field"

Revision ID: 3085a95a06a1
Revises: eee318ec3ce6
Create Date: 2017-03-09 10:24:02.530115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Boolean, Integer, String
from sqlalchemy.sql import column, table

from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.

revision = '3085a95a06a1'
down_revision = 'eee318ec3ce6'
branch_labels = None
depends_on = None


def upgrade():
    # Data migration
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        snap_table = table('snapshot',
                           column('id', Integer),
                           column('deleted', Boolean),
                           column('state', String),
                           column('num', String),
                           column('volume_id', String),
                           column('backup_id', String),
                           column('mountpoint', String),
                           column('size', String),
                           column('meta', String),
                           column('empty', Boolean))
        snap_drive_table = table('snapshot_drive_association',
                                 column('snapshot_id', String(36)),
                                 column('drive_id', String(36)))
        delete_association = snap_drive_table.delete().where(
            snap_drive_table.c.snapshot_id.in_(
                session.query(snap_table.c.id).filter(
                    snap_table.c.empty.is_(True))))
        session.execute(delete_association)
        session.execute(snap_table.delete().where(snap_table.c.empty.is_(True)))
        session.commit()
    finally:
        session.close()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'empty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('empty',
                                        mysql.BOOLEAN,
                                        server_default=sa.text("'0'"),
                                        autoincrement=False,
                                        nullable=True))
    # ### end Alembic commands ###
