""""cloud_resource_nullable_name"

Revision ID: 350e9a4a2489
Revises: d637725cfe39
Create Date: 2020-05-23 09:39:53.202212

"""
from alembic import op
from sqlalchemy import String, update, table, column
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision = '350e9a4a2489'
down_revision = 'd637725cfe39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'resource', 'name', existing_type=String(256), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    resource_table = table(
        'resource', column('id', String(36)), column('name', String(256)))
    upd_stmt = update(resource_table).values(
        name=resource_table.c.id).where(
        resource_table.c.name.is_(None))
    try:
        session.execute(upd_stmt)
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
    op.alter_column(
        'resource', 'name', existing_type=String(256), nullable=False)
    # ### end Alembic commands ###
