""""added_group_to_agent"

Revision ID: 3907fe291cf2
Revises: 51899a3772d1
Create Date: 2017-05-04 09:57:10.364163

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3907fe291cf2'
down_revision = '51899a3772d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('group_id', sa.String(length=36),
                                     nullable=True))
    op.create_foreign_key(
        'agent_ibfk_group', 'agent', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_ibfk_group', 'agent', type_='foreignkey')
    op.drop_column('agent', 'group_id')
    # ### end Alembic commands ###
