""""add_total_size_to_snapshot"

Revision ID: 41ac2aeac093
Revises: e9dfcff67045
Create Date: 2019-02-27 13:40:20.524849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String, select
import json


# revision identifiers, used by Alembic.
revision = '41ac2aeac093'
down_revision = 'e9dfcff67045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('total_size', sa.BigInteger(), nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        snapshot_table = table('snapshot', column('total_size', sa.BigInteger()),
                               column('meta', sa.TEXT()), column('id', String(36)))
        stmt = select([snapshot_table]).where(snapshot_table.c.total_size == 0)
        snapshots = session.execute(stmt)
        for i, snapshot in enumerate(snapshots):
            try:
                meta = json.loads(snapshot.meta)
                size = meta.get('size') or 0
            except (json.decoder.JSONDecodeError, AttributeError):
                size = 0
            stmt = update(snapshot_table).values(total_size=size).where(
                snapshot['id'] == snapshot_table.c.id)
            session.execute(stmt)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'total_size')
    # ### end Alembic commands ###
