""""fatcowless_dr"

Revision ID: 430da541e0be
Revises: cc36af074e8a
Create Date: 2018-05-11 16:44:37.088808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '430da541e0be'
down_revision = 'd789f6958a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cloud_agent',
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=False),
        sa.Column('api_url', sa.String(256), nullable=False),
        sa.Column('iscsi_address', sa.String(256), nullable=False),
        sa.ForeignKeyConstraint(['cloud_id'], ['cloud.id'], ),
        sa.PrimaryKeyConstraint('id'),
        )
    op.create_table(
        'cloud_volume',
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('cloud_agent_id', sa.String(36), nullable=False),
        sa.Column('device_name', sa.String(256), nullable=True),
        sa.Column('state', sa.Enum(
            'ATTACHING', 'ATTACHED', 'DETACHING', 'DETACHED'),
                  nullable=False, server_default='DETACHED'),
        sa.ForeignKeyConstraint(['cloud_agent_id'], ['cloud_agent.id'], ),
        sa.PrimaryKeyConstraint('id'),
        )
    bind = op.get_bind()
    session = Session(bind=bind)
    to_dynamic_stmt_agent = "ALTER TABLE `cloud_agent` ROW_FORMAT=DYNAMIC;"
    to_dynamic_stmt_volume = "ALTER TABLE `cloud_volume` ROW_FORMAT=DYNAMIC;"
    session.execute(to_dynamic_stmt_agent)
    session.execute(to_dynamic_stmt_volume)
    session.close()
    op.create_unique_constraint(
        'uc_cloud_id_api_url_deleted_at', 'cloud_agent', ['cloud_id',
                                                          'api_url', 'deleted_at'])
    op.add_column('drive', sa.Column('cloud_volume_id', sa.String(36),
                                     nullable=True))
    op.create_foreign_key('drive_ibfk_cloud_volume', 'drive', 'cloud_volume',
                          ['cloud_volume_id'], ['id'])
    op.add_column('snapshot', sa.Column('cloud_snapshot_id', sa.String(36),
                                        nullable=True))
    op.add_column('snapshot', sa.Column('cloud_volume_id', sa.String(36),
                                        nullable=True))
    op.create_foreign_key(
        'snapshot_ibfk_cloud_volume', 'snapshot', 'cloud_volume',
        ['cloud_volume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('snapshot_ibfk_cloud_volume', 'snapshot',
                       type_='foreignkey')
    op.drop_column('snapshot', 'cloud_volume_id')
    op.drop_column('snapshot', 'cloud_snapshot_id')
    op.drop_constraint('drive_ibfk_cloud_volume', 'drive', type_='foreignkey')
    op.drop_column('drive', 'cloud_volume_id')
    op.drop_table('cloud_volume')
    op.drop_table('cloud_agent')
    # ### end Alembic commands ###
