""""“esxi_host_datastore”"

Revision ID: 4451a81a7415
Revises: 875c236094ba
Create Date: 2017-10-20 15:22:26.234385

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4451a81a7415'
down_revision = '875c236094ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datastore_host',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('esxi_host_id', sa.String(length=36), nullable=False),
    sa.Column('esxi_datastore_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['esxi_datastore_id'], ['esxi_datastore.id'], ),
    sa.ForeignKeyConstraint(['esxi_host_id'], ['esxi_host.id'], ),
    sa.PrimaryKeyConstraint('id', 'esxi_host_id', 'esxi_datastore_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datastore_host')
    # ### end Alembic commands ###
