""""report_import_updated_at"

Revision ID: 457e1b52d5a0
Revises: ac24cf000c44
Create Date: 2023-08-02 07:22:46.900343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '457e1b52d5a0'
down_revision = 'ac24cf000c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reportimport', sa.Column('updated_at', sa.Integer(),
                                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reportimport', 'updated_at')
    # ### end Alembic commands ###
