""""failover_lock_columns"

Revision ID: 50c606a2bb38
Revises: 2027610f7083
Create Date: 2017-04-20 03:56:00.794708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c606a2bb38'
down_revision = '2027610f7083'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup', sa.Column('lock_owner', sa.String(length=256), nullable=True))
    op.add_column('backup', sa.Column('locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backup', 'locked')
    op.drop_column('backup', 'lock_owner')
    # ### end Alembic commands ###
