""""unprotected_state"

Revision ID: 51899a3772d1
Revises: 8bac85a6b1f9
Create Date: 2017-05-02 12:14:42.183386

"""
from alembic import op


# revision identifiers, used by Alembic.
from sqlalchemy.orm import Session

revision = '51899a3772d1'
down_revision = '453418424cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        session.execute("ALTER TABLE devicestate MODIFY COLUMN state "
                        "ENUM('unprotected', 'scheduled', 'running', 'idle', "
                        "'cancel', 'error') NOT NULL;")
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    bind = op.get_bind()
    session = Session(bind=bind)

    try:
        session.execute("ALTER TABLE devicestate MODIFY COLUMN state "
                        "ENUM('scheduled', 'running', 'idle', "
                        "'cancel', 'error') NOT NULL;")
    finally:
        session.close()
    # ### end Alembic commands ###
