""""state_mixin"

Revision ID: 53877d99024e
Revises: d83e608e20b3
Create Date: 2017-05-02 08:06:24.226477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53877d99024e'
down_revision = 'd83e608e20b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'state')
    op.drop_column('customer', 'state')
    op.drop_column('device', 'state')
    op.drop_column('drplan', 'state')
    op.drop_column('failover', 'state')
    op.drop_column('group', 'state')
    op.drop_column('partner', 'state')
    op.drop_column('vspherecredential', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vspherecredential', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('partner', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('group', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('failover', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('drplan', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('device', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('customer', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    op.add_column('agent', sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True))
    # ### end Alembic commands ###
