""""customer_phone_address_not_null"

Revision ID: 55739f28884a
Revises: 14c9909cb961
Create Date: 2017-08-21 10:30:41.301310

"""
from alembic import op
from sqlalchemy.orm import Session
from sqlalchemy import update, String
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '55739f28884a'
down_revision = '14c9909cb961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        customer_table = table('customer',
                               column('address', String(256)),
                               column('phone', String(256)))
        upd_address = update(customer_table).values(
            address='').where(customer_table.c.address.is_(None))
        upd_phone = update(customer_table).values(
            phone='').where(customer_table.c.phone.is_(None))
        session.execute(upd_address)
        session.execute(upd_phone)
        op.alter_column('customer', 'address',
                        existing_type=String(256), nullable=False, default='')
        op.alter_column('customer', 'phone',
                        existing_type=String(256), nullable=False, default='')
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'phone',
                    existing_type=String(256), nullable=True)
    op.alter_column('customer', 'address',
                    existing_type=String(256), nullable=True)
    # ### end Alembic commands ###
