""""mountpoint_default"

Revision ID: 5731fca8c174
Revises: b498ff3be45a
Create Date: 2018-07-09 10:34:18.689612

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import select, String, update, Boolean
from sqlalchemy.orm import Session
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5731fca8c174'
down_revision = 'b498ff3be45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mountpoint', sa.Column('default', sa.Boolean(),
                                          nullable=False, default=False))

    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        mountpoint_table = table('mountpoint',
                                 column('id', String(36)),
                                 column('default', Boolean),
                                 column('deleted_at', sa.Integer()))
        stmt = select([mountpoint_table]).where(
            mountpoint_table.c.deleted_at == 0)
        mountpoint_id = session.execute(stmt).scalar()
        if mountpoint_id:
            upd_stmt = update(mountpoint_table).values(
                default=True).where(
                mountpoint_table.c.id == mountpoint_id)
            session.execute(upd_stmt)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mountpoint', 'default')
    # ### end Alembic commands ###
