""""snapshot_type"

Revision ID: 59ea8eab433e
Revises: 541673c481bd
Create Date: 2017-07-11 10:53:28.496413

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '59ea8eab433e'
down_revision = '12015f05eab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snapshot', sa.Column('type', sa.Enum('FULL', 'INCREMENTAL', name='snapshot_type'), nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    snapshot_table = table('snapshot', column('type'))
    upd_stmt = sa.update(snapshot_table).values(type='INCREMENTAL')
    try:
        session.execute(upd_stmt)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snapshot', 'type')
    # ### end Alembic commands ###
