""""added_site_group_agent"

Revision ID: 5bfe31fe2892
Revises: 6b7f641658d1
Create Date: 2017-01-10 11:16:35.499039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5bfe31fe2892'
down_revision = '6b7f641658d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.Enum('solo', 'multi', name='agent_types'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('device', sa.Column('agent_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('device_ibfk_2', 'device', 'agent', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_ibfk_2', 'device', type_='foreignkey')
    op.drop_column('device', 'agent_id')
    op.drop_table('agent')
    op.drop_table('group')
    op.drop_table('site')
    # ### end Alembic commands ###
