""""cloud_agent_undo_assignment"

Revision ID: 5d3fea32d151
Revises: 116f5bf4c7dc
Create Date: 2018-10-29 11:57:34.857568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String, select, Integer
import datetime

# revision identifiers, used by Alembic.
revision = '5d3fea32d151'
down_revision = '116f5bf4c7dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('volume_ibfk_cloud_agent', 'cloud_volume',
                       type_='foreignkey')
    op.drop_column('cloud_volume', 'assigned_cloud_agent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_volume', sa.Column('assigned_cloud_agent_id',
                                            sa.String(length=36),
                                            nullable=True))
    op.create_foreign_key('volume_ibfk_cloud_agent', 'cloud_volume',
                          'cloud_agent', ['assigned_cloud_agent_id'], ['id'])
    # ### end Alembic commands ###
