""""move_os_vol_id_to_drive"

Revision ID: 61039ec12750
Revises: 3085a95a06a1
Create Date: 2017-03-28 16:07:13.347945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61039ec12750'
down_revision = 'fc2be49722da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'drive', sa.Column('os_volume_id', sa.String(length=36), nullable=True))
    op.drop_column('failover', 'volume_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failover', sa.Column('volume_id', mysql.VARCHAR(
        collation='utf8mb4_unicode_ci', length=36), nullable=True))
    op.drop_column('drive', 'os_volume_id')
    # ### end Alembic commands ###
