""""failback_states"

Revision ID: 62b9a635c7ab
Revises: fd808cf92f7b
Create Date: 2018-12-14 14:57:23.883878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62b9a635c7ab'
down_revision = 'fd808cf92f7b'
branch_labels = None
depends_on = None
old_cs_types = sa.Enum('CLOUD_SITE', 'DUMMY_SITE')
new_cs_types = sa.Enum('CLOUD_SITE', 'DUMMY_SITE', 'DUMMY_FAILBACK')
old_fbsnap_types = sa.Enum('BACKUP', 'FATCOW')
new_fbsnap_types = sa.Enum('BACKUP', 'FATCOW', 'CLOUD')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'cloudsite', 'cs_type', existing_type=new_cs_types, nullable=False,
        existing_server_default=sa.text("'CLOUD_SITE'"))
    op.alter_column(
        'failback_snapshot', 'type', existing_type=new_fbsnap_types,
        nullable=False, existing_server_default=sa.text("'CLOUD'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ct = sa.sql.table('cloudsite', sa.sql.column('cs_type', new_cs_types))
    op.execute(ct.update().where(ct.c.cs_type.in_(
        ['DUMMY_FAILBACK'])).values(cs_type='DUMMY_SITE'))
    op.alter_column(
        'cloudsite', 'cs_type', existing_type=old_cs_types, nullable=False,
        existing_server_default=sa.text("'CLOUD_SITE'"))
    fst = sa.sql.table('failback_snapshot', sa.sql.column('type',
                                                          new_fbsnap_types))
    op.execute(fst.update().where(fst.c.type.in_(
        ['CLOUD'])).values(type='FATCOW'))
    op.alter_column(
        'failback_snapshot', 'type', existing_type=old_fbsnap_types,
        nullable=False, existing_server_default=sa.text("'FATCOW'"))
    # ### end Alembic commands ###
