""""add table ssh_key"

Revision ID: 654de385756b
Revises: 541673c481bd
Create Date: 2017-07-20 15:23:05.075055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '654de385756b'
down_revision = '59ea8eab433e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('ssh_key_id', sa.String(length=36), nullable=True))
    op.create_table('ssh_key',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ssh_key', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_foreign_key('agent_ibfk_ssh_key', 'agent', 'ssh_key', ['ssh_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_ibfk_ssh_key', 'agent', type_='foreignkey')
    op.drop_table('ssh_key')
    op.drop_column('agent', 'ssh_key_id')
    # ### end Alembic commands ###

