""""device_removed_cpu_ram"

Revision ID: 683f50a0f0f7
Revises: 3907fe291cf2
Create Date: 2017-05-19 14:50:53.386042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '683f50a0f0f7'
down_revision = 'a9d0e1c399ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'cpu')
    op.drop_column('device', 'ram')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('ram', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('cpu', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
