""""initial"

Revision ID: 69eaf6aa6fcc
Revises: 
Create Date: 2016-12-23 15:15:20.571837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eaf6aa6fcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloudsite',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.TEXT(), nullable=True),
    sa.Column('public_ip', sa.String(length=15), nullable=True),
    sa.Column('stack_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drplan',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('plan', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'name'),
                    mysql_row_format='DYNAMIC'
    )
    op.create_index(op.f('ix_drplan_name'), 'drplan', ['name'], unique=False)
    op.create_table('backup',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_created'), 'backup', ['created'], unique=False)
    op.create_table('failover',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=False),
    sa.Column('backup_id', sa.String(length=36), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('ram', sa.Integer(), nullable=True),
    sa.Column('port_id', sa.String(length=36), nullable=True),
    sa.Column('floating_ip', sa.String(length=36), nullable=True),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('volume_id', sa.String(length=36), nullable=True),
    sa.Column('tmp_snap_id', sa.String(length=36), nullable=True),
    sa.Column('container_id', sa.String(length=36), nullable=True),
    sa.Column('cloudsite_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backup.id'], ),
    sa.ForeignKeyConstraint(['cloudsite_id'], ['cloudsite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshot',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=True),
    sa.Column('volume_id', sa.String(length=36), nullable=True),
    sa.Column('backup_id', sa.String(length=36), nullable=True),
    sa.Column('mountpoint', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['backup_id'], ['backup.id'], ),
    sa.PrimaryKeyConstraint('num')
    )
    op.create_index(op.f('ix_snapshot_id'), 'snapshot', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_snapshot_id'), table_name='snapshot')
    op.drop_table('snapshot')
    op.drop_table('failover')
    op.drop_index(op.f('ix_backup_created'), table_name='backup')
    op.drop_table('backup')
    op.drop_index(op.f('ix_drplan_name'), table_name='drplan')
    op.drop_table('drplan')
    op.drop_table('device')
    op.drop_table('cloudsite')
    op.drop_table('customer')
    # ### end Alembic commands ###
