""""failback_dummysite_id"

Revision ID: 6e9445ee5340
Revises: b532c6a989db
Create Date: 2018-12-28 10:43:12.690685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e9445ee5340'
down_revision = '9401aa720b0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('failback', sa.Column('dummysite_id', sa.String(length=36),
                                        nullable=True))
    op.create_foreign_key('failback_ibfk_dummysite', 'failback', 'cloudsite',
                          ['dummysite_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('failback_ibfk_dummysite', 'failback',
                       type_='foreignkey')
    op.drop_column('failback', 'dummysite_id')
    # ### end Alembic commands ###
