"""budget_purpose"

Revision ID: 6f55e6e46bd8
Revises: 47e873452902
Create Date: 2020-08-31 14:16:20.366226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f55e6e46bd8'
down_revision = '47e873452902'
branch_labels = None
depends_on = None

budget_purposes = sa.Enum('BUDGET', 'BUSINESS_UNIT', 'TEAM', 'PROJECT', 'CICD',
                          'MLAI', 'ASSET_POOL')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('purpose', budget_purposes,
                                      nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budget', 'purpose')
    # ### end Alembic commands ###
