""""2.3 remove old fields from budget table"

Revision ID: 732c0919c1bd
Revises: 24acd1baab5b
Create Date: 2020-09-06 23:56:08.890126

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '732c0919c1bd'
down_revision = '24acd1baab5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_budget_fk', 'budget', type_='foreignkey')
    op.drop_column('budget', 'type')
    op.drop_column('budget', 'employee_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget', sa.Column('employee_id', sa.String(36),
                                      nullable=True))
    op.add_column('budget',
                  sa.Column('type',
                            sa.Enum('PROJECT', 'BUSINESS_UNIT', 'EMPLOYEE'),
                            nullable=False))
    op.create_foreign_key('employee_budget_fk', 'budget', 'employee',
                          ['employee_id'], ['id'])
    # ### end Alembic commands ###
