""""device_name_required"

Revision ID: 78f19da81b1e
Revises: 50339b903913
Create Date: 2017-06-07 14:23:55.276486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String, select

# revision identifiers, used by Alembic.
revision = '78f19da81b1e'
down_revision = '01bfee5f7666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        device_table = table('device', column('name', String(20)),
                             column('id', String(36)))
        stmt = select([device_table]).where(device_table.c.name.is_(None))
        devices = session.execute(stmt)
        for i, device in enumerate(devices):
            new_name = 'device_' + str(i)
            stmt = update(device_table).values(name=new_name).where(
                device['id'] == device_table.c.id,)
            session.execute(stmt)
        session.commit()
    finally:
        session.close()
    op.alter_column('device', 'name', existing_type=sa.String(length=256),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'name',  existing_type=sa.String(length=256),
                    nullable=True)
    # ### end Alembic commands ###
