""""added_last_seen_agent_to_device"

Revision ID: 7da1a8ebd937
Revises: 70d6376c23a0
Create Date: 2018-04-12 15:16:35.793989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7da1a8ebd937'
down_revision = '70d6376c23a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('last_agent_id', sa.String(length=36),
                                      nullable=True))
    op.create_foreign_key('device_ibfk_agent', 'device', 'agent',
                          ['last_agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_ibfk_agent', 'device', type_='foreignkey')
    op.drop_column('device', 'last_agent_id')
    # ### end Alembic commands ###
