""""add_project_name_to_cs"

Revision ID: 7f37849091e8
Revises: cb3a6cdaa72c
Create Date: 2017-12-15 09:56:06.614080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f37849091e8'
down_revision = 'cb3a6cdaa72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsite', sa.Column('project_name', sa.String(length=256),
                                         nullable=False, default='unknown'))
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        cs_table = table('cloudsite', column('project_name', sa.String()))
        upd = update(cs_table).values(project_name='unknown')
        session.execute(upd)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloudsite', 'project_name')
    # ### end Alembic commands ###
