""""root_unit_purpose"

Revision ID: 865bb21cc4a4
Revises: 6f55e6e46bd8
Create Date: 2020-09-03 13:25:18.023001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import select
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '865bb21cc4a4'
down_revision = '6f55e6e46bd8'
branch_labels = None
depends_on = None

purposes = sa.Enum('BUDGET', 'BUSINESS_UNIT', 'TEAM', 'PROJECT', 'CICD',
                   'MLAI', 'ASSET_POOL')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        partner_table = sa.table(
            'partner',
            sa.Column('parent_id', sa.String(36)),
            sa.Column('budget_id', sa.String(36))
        )
        stmt = select([partner_table]).where(
            partner_table.c.parent_id.is_(None))
        root_partners = session.execute(stmt)
        budget_ids = list(map(lambda x: x['budget_id'], root_partners))
        budget_table = sa.table(
            'budget',
            sa.Column('id', sa.String(36)),
            sa.Column('purpose', purposes)
        )
        update_stmt = sa.update(budget_table).values(
            purpose='BUSINESS_UNIT'
        ).where(
            budget_table.c.id.in_(budget_ids))
        session.execute(update_stmt)
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
