""""add_enable_field_for_discover_info"

Revision ID: 8f9717cc2d71
Revises: a122b4004241
Create Date: 2021-10-11 13:53:36.157813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import select, String, update, Boolean


# revision identifiers, used by Alembic.
revision = '8f9717cc2d71'
down_revision = 'a122b4004241'
branch_labels = None
depends_on = None
CHUNK_UPDATE_SIZE = 100


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discovery_info', sa.Column('enabled', sa.Boolean(),
                                              default=True, nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    cloud_acc_table = table('cloudaccount',
                            column('id', sa.String(36)))
    cloud_accounts_stmt = select([cloud_acc_table.c.id])
    cloud_account_ids = [cloud_info['id'] for cloud_info in
                         session.execute(cloud_accounts_stmt)]
    d_info_table = table('discovery_info',
                         column('id', String(36)),
                         column('cloud_account_id', String(36)),
                         column('enabled', Boolean()))
    try:
        for i in range(0, len(cloud_account_ids), CHUNK_UPDATE_SIZE):
            cloud_account_id_chunk = cloud_account_ids[i:i + CHUNK_UPDATE_SIZE]
            update_stmt = update(d_info_table).values(enabled=True).where(
                d_info_table.c.cloud_account_id.in_(cloud_account_id_chunk))
            session.execute(update_stmt)
        session.commit()
    finally:
        session.close()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('discovery_info', 'enabled')
