""""cloud_agent_number"

Revision ID: 9fa1385b538c
Revises: e156d7295f1a
Create Date: 2019-06-27 09:52:47.178710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import String, update


# revision identifiers, used by Alembic.
revision = '9fa1385b538c'
down_revision = 'e156d7295f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_agent', sa.Column('num', sa.Integer(), nullable=True))
    op.create_unique_constraint('uc_cstmr_num_del_at', 'cloud_agent',
                                ['customer_id', 'num', 'deleted_at'])
    op.add_column('cloud_agent', sa.Column('instance_id', sa.String(length=36),
                                           nullable=True))
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        cloud_agent_table = table('cloud_agent',
                                  column('id', String(36)),
                                  column('instance_id', String(36)))
        upd_stmt = update(cloud_agent_table).values(
            instance_id=cloud_agent_table.c.id)
        session.execute(upd_stmt)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cloud_agent_ibfk_1', 'cloud_agent', type_='foreignkey')
    op.drop_constraint('uc_cstmr_num_del_at', 'cloud_agent', type_='unique')
    op.create_foreign_key('cloud_agent_ibfk_1', 'cloud_agent', 'customer',
                          ['customer_id'], ['id'])
    op.drop_column('cloud_agent', 'num')
    op.drop_column('cloud_agent', 'instance_id')
    # ### end Alembic commands ###
