""""add_resource_cloud_acc_res_type_active_index"

Revision ID: a6056e705872
Revises: 059752aeab47
Create Date: 2020-10-30 06:57:09.110421

"""
import os
from pymongo import MongoClient
from config_client.client import Client as EtcdClient

# revision identifiers, used by Alembic.
revision = 'a6056e705872'
down_revision = '059752aeab47'
branch_labels = None
depends_on = None
DEFAULT_ETCD_HOST = 'etcd-client'
DEFAULT_ETCD_PORT = 80
INDEX_NAME = 'CloudAccIdResTypeActiveIndex'


def _get_etcd_config_client():
    etcd_host = os.environ.get('HX_ETCD_HOST', DEFAULT_ETCD_HOST)
    etcd_port = os.environ.get('HX_ETCD_PORT', DEFAULT_ETCD_PORT)
    config_cl = EtcdClient(host=etcd_host, port=int(etcd_port))
    return config_cl


def _get_resources_collection():
    config_cl = _get_etcd_config_client()
    mongo_params = config_cl.mongo_params()
    mongo_conn_string = "mongodb://%s:%s@%s:%s" % mongo_params[:-1]
    mongo_client = MongoClient(mongo_conn_string)
    return mongo_client.restapi.resources


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    resources_collection = _get_resources_collection()
    resources_collection.create_index([('cloud_account_id', 1),
                                      ('resource_type', 1), ('active', 1)],
                                      name=INDEX_NAME, background=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    resources_collection = _get_resources_collection()
    indexes = [x['name'] for x in resources_collection.list_indexes()]
    if INDEX_NAME in indexes:
        resources_collection.drop_index(INDEX_NAME)
    # ### end Alembic commands ###
