""""customer_added_new_fields"

Revision ID: ad8407118b8a
Revises: b6f7ce253259
Create Date: 2017-05-05 15:17:06.564902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad8407118b8a'
down_revision = 'b6f7ce253259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('active', sa.Boolean(), default=True))
    op.add_column('customer', sa.Column('address', sa.String(length=256), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'active')
    # ### end Alembic commands ###
