""""cloud_credentials_account_id"

Revision ID: b6a5c7a77110
Revises: c8f2cab6e4d0
Create Date: 2020-05-07 10:22:14.185232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6a5c7a77110'
down_revision = '311bd7d6b356'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudcredentials', sa.Column(
        'account_id', sa.String(256), nullable=True))
    op.create_unique_constraint(
        'uc_account_type_bu_id_del_at', 'cloudcredentials',
        ['account_id', 'type', 'business_unit_id', 'deleted_at'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_account_type_bu_id_del_at',
                       'cloudcredentials', type_='unique')
    op.drop_column('cloudcredentials', 'account_id')
    # ### end Alembic commands ###
