"""vmware_cloud_volumes

Revision ID: bcd2ac6d3474
Revises: f1cae25c9c09
Create Date: 2019-03-03 13:17:29.618965

Migration moved to ff5f881f5088.
This file must be left to support clusters on this alembic version.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcd2ac6d3474'
down_revision = 'f1cae25c9c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
