""""added_parnter"

Revision ID: bdd2c6f1942c
Revises: 69eaf6aa6fcc
Create Date: 2016-12-28 14:34:16.127134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd2c6f1942c'
down_revision = '69eaf6aa6fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customer', sa.Column('partner_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('customer_ibfk_1', 'customer', 'partner', ['partner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_ibfk_1', 'customer', type_='foreignkey')
    op.drop_column('customer', 'partner_id')
    op.drop_table('partner')
    # ### end Alembic commands ###
