""""cs_parent_id"

Revision ID: c1095c9b7b6a
Revises: f2f07bc2fd82
Create Date: 2019-09-25 14:35:38.377085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1095c9b7b6a'
down_revision = 'f2f07bc2fd82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsite', sa.Column('parent_cs_id', sa.String(length=36),
                                         nullable=True))
    op.create_foreign_key('cs_parent', 'cloudsite', 'cloudsite',
                          ['parent_cs_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cs_parent', 'cloudsite', type_='foreignkey')
    op.drop_column('cloudsite', 'parent_cs_id')
    # ### end Alembic commands ###
