""""“drplan_add_deleted_at_unique”"

Revision ID: c3c4691bec55
Revises: 541673c481bd
Create Date: 2017-07-19 09:25:44.725436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import update, String, select, and_


# revision identifiers, used by Alembic.
revision = 'c3c4691bec55'
down_revision = '541673c481bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_drplan_name_customer_unique', 'drplan',
                    ['customer_id', 'name', 'deleted_at'], unique=True)
    op.drop_index('customer_id', table_name='drplan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        drplan_table = table('drplan',
                             column('name', String(256)),
                             column('id', String(36)),
                             column('customer_id', String(36)))
        stmt = select([drplan_table])
        drplans = session.execute(stmt)
        for drplan in drplans:
            new_name = drplan_table.c.name+'-'+drplan_table.c.id
            stmt = update(drplan_table).values(
                name=new_name).where(
                and_(
                    drplan['id'] != drplan_table.c.id,
                    drplan['name'] == drplan_table.c.name,
                    drplan['customer_id'] == drplan_table.c.customer_id
                )
            )
            session.execute(stmt)
        session.commit()
    finally:
        session.close()
    op.create_index('customer_id', 'drplan',
                    ['customer_id', 'name'], unique=True)
    op.drop_index('idx_drplan_name_customer_unique', table_name='drplan')
    # ### end Alembic commands ###
