""""schedules"

Revision ID: c665216914b3
Revises: 40523986854c
Create Date: 2017-01-19 10:38:21.741588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c665216914b3'
down_revision = '40523986854c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('update_time', sa.Integer(), nullable=False),
    sa.Column('target_rpo', sa.Integer(), nullable=False),
    sa.Column('idle_until', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('scheduled', 'running', 'idle', 'cancel', 'error', name='state'), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    # ### end Alembic commands ###
