""""added not null constraint for source budget"

Revision ID: c8ec43fa40ac
Revises: 350e9a4a2489
Create Date: 2020-05-29 00:43:16.439606

"""
from datetime import datetime

from alembic import op
from sqlalchemy.orm import Session
import sqlalchemy as sa
# from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = 'c8ec43fa40ac'
down_revision = '339120401327'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)
    table_ = sa.table('assignment_request',
                      sa.column('source_budget_id', sa.String(36)))
    delete_invalid_requests = sa.delete(
        table_
    ).where(
        table_.c.source_budget_id.is_(None)
    )
    try:
        session.execute(delete_invalid_requests)
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_request', 'source_budget_id',
                    existing_type=sa.String(36), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment_request', 'source_budget_id',
                    existing_type=sa.String(36), nullable=True)
    # ### end Alembic commands ###
