""""Make owner is not nullable field in resource assignment history"

Revision ID: c8f2cab6e4d0
Revises: 66796766fac0
Create Date: 2020-05-05 11:42:52.805658

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import String
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = 'c8f2cab6e4d0'
down_revision = '66796766fac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    resource_assignment_history_table = sa.table(
        'resource_assignment_history',
        sa.Column('owner_id', sa.String(36)))
    try:
        session.execute(resource_assignment_history_table.delete().where(
            resource_assignment_history_table.c.owner_id.is_(None)))
        session.commit()
    finally:
        session.close()
    op.alter_column('resource_assignment_history', 'owner_id',
                    existing_type=String(36), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_assignment_history', 'owner_id',
                    existing_type=String(36), nullable=True)
    # ### end Alembic commands ###
