""""failover_scripts"

Revision ID: cb3a6cdaa72c
Revises: d56f9da1f7bd
Create Date: 2017-10-31 16:38:31.195609

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb3a6cdaa72c'
down_revision = 'd56f9da1f7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'failover_script',
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('failover_id', sa.String(36), nullable=False),
        sa.Column('script_id', sa.String(36), nullable=False),
        sa.Column('parameters', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['failover_id'], ['failover.id'], ),
        sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failover_script')
    # ### end Alembic commands ###
