""""drive_num"

Revision ID: cc8a74570004
Revises: 3de565d98c77
Create Date: 2018-08-31 08:50:43.937833

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc8a74570004'
down_revision = '8c81d4727bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drive', sa.Column('drive_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drive', 'drive_number')
    # ### end Alembic commands ###
