""""cloud_agent_role"

Revision ID: d093179183b5
Revises: ff5f881f5088
Create Date: 2019-06-03 10:12:41.235085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = 'd093179183b5'
down_revision = '6eeb9a2f5207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_agent', sa.Column(
        'role', sa.Enum('REGULAR', 'CABRIO', 'FAILBACK'), nullable=False))
    ca_table = sa.table('cloud_agent', sa.Column(
        'role', sa.Enum('REGULAR', 'CABRIO', 'FAILBACK'), nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    set_ca_role = sa.update(ca_table).values(role='REGULAR')
    try:
        session.execute(set_ca_role)
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_agent', 'role')
    # ### end Alembic commands ###
