""""make an owner_id FK for resources"

Revision ID: d637725cfe39
Revises: a73a5a839f5a
Create Date: 2020-05-21 13:09:36.505854

"""
from datetime import datetime

from alembic import op
from sqlalchemy.orm import Session
from sqlalchemy.sql import table, column
from sqlalchemy import select, String, update, Integer

# revision identifiers, used by Alembic.

revision = 'd637725cfe39'
down_revision = 'fb8d7eb932dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = Session(bind=bind)
    table_ = table('employee', column('id', String(36)))
    empl_ids = [empl['id'] for empl in session.execute(select([table_.c.id]))]
    table_ = table('resource',
                   column('id', String(36)),
                   column('employee_id', String(36)),
                   column('budget_id', String(36)))
    resource_stmt = select(
        [table_.c.id]
    ).where(
        table_.c.employee_id.notin_(empl_ids)
    )
    resource_ids = [res['id'] for res in session.execute(resource_stmt)]
    unassign_resources_stmt = update(
        table_
    ).values(
        employee_id=None,
        budget_id=None
    ).where(
        table_.c.id.in_(resource_ids)
    )
    table_ = table('resource_assignment_history',
                   column('resource_id', String(36)),
                   column('deleted_at', Integer))
    delete_from_assignment_history_stmt = update(
        table_
    ).values(
        deleted_at=int(datetime.utcnow().timestamp())
    ).where(
        table_.c.resource_id.in_(resource_ids)
    )
    try:
        session.execute(unassign_resources_stmt)
        session.execute(delete_from_assignment_history_stmt)
        session.commit()
    except Exception:
        session.rollback()
        raise
    finally:
        session.close()

    op.create_foreign_key('fk_resource_employee_id', 'resource', 'employee',
                          ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_resource_employee_id', 'resource',
                       type_='foreignkey')
    # ### end Alembic commands ###
