""""acura_models_removed"

Revision ID: df7d2f7ed7ee
Revises: d41c82067a5b
Create Date: 2020-06-26 14:47:30.036983

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'df7d2f7ed7ee'
down_revision = '55f1e54a4579'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_table('failback_snapshot')
    op.drop_table('failback_device')
    op.drop_table('failover_script')
    op.drop_table('payload')
    op.drop_table('snapshot_drive_association')
    op.drop_table('snapshot')
    op.drop_table('drive')
    op.drop_table('failover')
    op.drop_table('backup')
    op.drop_table('device')
    op.drop_table('agent')
    op.drop_table('ssh_key')
    op.drop_table('failback')
    op.drop_table('schedule')
    op.drop_table('script')
    op.drop_table('cloudsite')
    op.drop_table('device_state')
    op.drop_table('datastore_host')
    op.drop_table('esxi_host')
    op.drop_table('esxi_datastore')
    op.drop_table('cloud_volume')
    op.drop_table('cloud_agent')
    op.drop_table('drplan')
    op.drop_table('retention')
    op.drop_table('group')
    op.drop_constraint('fk_customer_cloud_id', 'customer', type_='foreignkey')
    op.drop_table('cloud')
    op.drop_table('customer')
    op.drop_table('mountpoint')


def downgrade():
    op.create_table(
        'mountpoint',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('mountpoint', sa.TEXT(), nullable=False),
        sa.Column('size', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('is_cnr', sa.Boolean(), default=True, nullable=False),
        sa.Column('default', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'customer',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(256), nullable=True),
        sa.Column('email', sa.String(256), nullable=True),
        sa.Column('partner_id', sa.String(36), nullable=False),
        sa.Column('default_group_id', sa.String(36), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('address', sa.String(256), nullable=False),
        sa.Column('phone', sa.String(256), nullable=False),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('mountpoint_id', sa.String(36), nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=True),
        sa.Column('cloud_overlay', sa.TEXT(), nullable=False),
        sa.Column('agent_override', sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(['mountpoint_id'], ['mountpoint.id'],
                                name='customer_ibfk_2'),
        sa.ForeignKeyConstraint(['partner_id'], ['partner.id'],
                                name='customer_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cloud',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('type',
                  sa.Enum('OPENSTACK', 'OPENSTACK_CNR', 'FAKE', 'AWS_CNR',
                          'OPENSTACK_HUAWEI_CNR', 'ALIBABA_CNR', 'VMWARE_CNR',
                          'AZURE_CNR', 'YANDEX_CNR'), nullable=False),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('endpoint', sa.String(256), nullable=True),
        sa.Column('username', sa.String(256), nullable=True),
        sa.Column('password', sa.BLOB(), nullable=True),
        sa.Column('salt', sa.String(256), nullable=True),
        sa.Column('extra_args', sa.TEXT(), nullable=True),
        sa.Column('default', sa.Boolean(), autoincrement=False, nullable=False),
        sa.Column('customer_id', sa.String(36), nullable=True),
        sa.Column('managed', sa.Boolean(), autoincrement=False, nullable=False),
        sa.Column('partner_id', sa.String(36), nullable=True),
        sa.Column('state_description', sa.TEXT(), nullable=False),
        sa.Column('validation_state',
                  sa.Enum('NOT_VALIDATED', 'VALIDATED', 'VALIDATING', 'ERROR'),
                  nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='cloud_customer_fk'),
        sa.ForeignKeyConstraint(['partner_id'], ['partner.id'],
                                name='cloud_partner_fk'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_foreign_key(
        'fk_customer_cloud_id', 'customer', 'cloud', ['cloud_id'], ['id'])

    op.create_table(
        'group',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('customer_id', sa.String(36), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='group_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'retention',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.String(36), nullable=True),
        sa.Column('daily', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('weekly', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('monthly', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('annually', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('keep_last', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'drplan',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('customer_id', sa.String(36), nullable=True),
        sa.Column('plan', sa.TEXT(), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='drplan_ibfk_customer'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cloud_agent',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('api_url', sa.String(256), nullable=True),
        sa.Column('iscsi_address', sa.String(256), nullable=True),
        sa.Column('customer_id', sa.String(36), nullable=False),
        sa.Column('cloud_config', sa.TEXT(), nullable=True),
        sa.Column('last_reported', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('version', sa.String(32), nullable=True),
        sa.Column('vmware_host', sa.String(256), nullable=True),
        sa.Column('num', sa.Integer, autoincrement=False, nullable=True),
        sa.Column('instance_id', sa.String(36), nullable=True),
        sa.Column('role', sa.Enum('REGULAR', 'CABRIO', 'FAILBACK'), nullable=False),
        sa.Column('update_enabled', sa.Boolean(), nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=True),
        sa.Column('deprecated', sa.Boolean(), nullable=False),
        sa.Column('backed_ips', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['cloud_id'], ['cloud.id'], name='cloud_agent_cloud_fk'),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='cloud_agent_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cloud_volume',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('cloud_agent_id', sa.String(36), nullable=True),
        sa.Column('device_name', sa.String(256), nullable=True),
        sa.Column('state',
                  sa.Enum('ATTACHING', 'ATTACHED', 'DETACHING', 'DETACHED'),
                  default='DETACHED', nullable=False),
        sa.Column('vmware_disk_file', sa.String(256), nullable=True),
        sa.Column('vmware_machine_id', sa.String(256), nullable=True),
        sa.ForeignKeyConstraint(['cloud_agent_id'], ['cloud_agent.id'],
                                name='cloud_volume_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'esxi_datastore',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('size', sa.BigInteger(), autoincrement=False, nullable=True),
        sa.Column('free', sa.BigInteger(), autoincrement=False, nullable=True),
        sa.Column('maintenance_mode',
                  sa.Enum('inMaintenance', 'enteringMaintenance', 'normal'),
                  nullable=False),
        sa.Column('accessible', sa.Boolean(), nullable=True),
        sa.Column('overall_status', sa.Enum('GRAY', 'GREEN', 'RED', 'YELLOW'),
                  nullable=False),
        sa.Column('update_time', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=False),
        sa.ForeignKeyConstraint(['cloud_id'], ['cloud.id'],
                                name='datastore_cloud_fk'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'esxi_host',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('hostname', sa.String(256), nullable=False),
        sa.Column('address', sa.String(39), nullable=False),
        sa.Column('update_time', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=False),
        sa.ForeignKeyConstraint(['cloud_id'], ['cloud.id'],
                                name='host_cloud_fk'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'datastore_host',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('esxi_host_id', sa.String(36), nullable=False),
        sa.Column('esxi_datastore_id', sa.String(36), nullable=False),
        sa.ForeignKeyConstraint(['esxi_datastore_id'], ['esxi_datastore.id'],
                                name='datastore_host_ibfk_1'),
        sa.ForeignKeyConstraint(['esxi_host_id'], ['esxi_host.id'],
                                name='datastore_host_ibfk_2'),
        sa.PrimaryKeyConstraint('id', 'esxi_host_id', 'esxi_datastore_id'),
    )
    op.create_table(
        'device_state',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('update_time', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('state',
                  sa.Enum('unprotected', 'scheduled', 'running', 'idle',
                          'cancel', 'error', 'blocked'), nullable=False),
        sa.Column('last_error', sa.Integer(), autoincrement=False,
                  nullable=True),
        sa.Column('idle_until', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('process',
                  sa.Enum('replicating', 'canceling', 'idle', 'deleting'),
                  nullable=True),
        sa.Column('progress', sa.Integer(), autoincrement=False, nullable=True),
        sa.Column('force_full', sa.Boolean(), autoincrement=False,
                  nullable=False),
        sa.Column('last_protection_state',
                  sa.Enum('unprotected', 'protected', 'parked', 'error',
                          'replicating', 'warned'), nullable=False),
        sa.Column('last_backup_report', sa.Integer(), autoincrement=False,
                  nullable=True),
        sa.CheckConstraint('`force_full` in (0,1)', name='CONSTRAINT_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'cloudsite',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('state',
                  sa.Enum('PENDING', 'CREATING', 'UPDATING', 'DELETING',
                          'DETACHING', 'DELETED', 'DETACHED', 'RUNNING',
                          'ROLLING_BACK', 'ERROR'), default='PENDING',
                  nullable=True),
        sa.Column('name', sa.String(256), nullable=True),
        sa.Column('customer_id', sa.String(36), nullable=True),
        sa.Column('plan', sa.TEXT(), nullable=True),
        sa.Column('public_ip', sa.String(15), nullable=True),
        sa.Column('stack_id', sa.String(36), nullable=True),
        sa.Column('project_id', sa.String(36), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('error_cause', sa.TEXT(), nullable=True),
        sa.Column('remove_project', sa.Boolean(), nullable=True),
        sa.Column('device_timestamps', sa.TEXT(), nullable=True),
        sa.Column('timestamp', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('project_name', sa.String(256), nullable=False),
        sa.Column('cloud_type',
                  sa.Enum('OPENSTACK', 'OPENSTACK_CNR', 'FAKE', 'AWS_CNR',
                          'OPENSTACK_HUAWEI_CNR', 'ALIBABA_CNR', 'VMWARE_CNR',
                          'AZURE_CNR', 'YANDEX_CNR'), nullable=False),
        sa.Column('cs_type',
                  sa.Enum('CLOUD_SITE', 'DUMMY_SITE', 'DUMMY_FAILBACK',
                          'DUMMY_FAILOVER'), default='CLOUD_SITE',
                  nullable=False),
        sa.Column('ttl', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('cloud_config', sa.TEXT(), nullable=True),
        sa.Column('parent_cs_id', sa.String(36), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='cloudsite_ibfk_1'),
        sa.ForeignKeyConstraint(['parent_cs_id'], ['cloudsite.id'],
                                name='cs_parent'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'script',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('script', sa.TEXT(), nullable=False),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('customer_id', sa.String(36), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='script_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'schedule',
        sa.Column('target_rpo', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('owner_id', sa.String(36), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'failback',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('name', sa.String(256), nullable=True),
        sa.Column('customer_id', sa.String(36), nullable=False),
        sa.Column('cloudsite_id', sa.String(36), nullable=True),
        sa.Column('plan', sa.TEXT(), nullable=False),
        sa.Column('state', sa.Enum('INCOMPLETE', 'IDLE', 'READY', 'RUNNING',
                                   'SYNCHRONIZED', 'ERROR', 'CANCEL',
                                   'CANCELLED', 'CANCELLING', 'PREPARING'),
                  nullable=False),
        sa.Column('update_time', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('dummysite_id', sa.String(36), nullable=True),
        sa.Column('project_id', sa.String(36), nullable=True),
        sa.Column('type', sa.Enum('OPENSTACK', 'HUAWEI', 'VMWARE'),
                  default='VMWARE', nullable=False),
        sa.Column('cloud_id', sa.String(36), nullable=False),
        sa.ForeignKeyConstraint(['cloud_id'], ['cloud.id'],
                                name='failback_cloud_fk'),
        sa.ForeignKeyConstraint(['cloudsite_id'], ['cloudsite.id'],
                                name='failback_ibfk_1'),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='failback_ibfk_2'),
        sa.ForeignKeyConstraint(['dummysite_id'], ['cloudsite.id'],
                                name='failback_ibfk_dummysite'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ssh_key',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('ssh_key', sa.TEXT(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'agent',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('name', sa.String(256), nullable=True),
        sa.Column('description', sa.TEXT(), nullable=True),
        sa.Column('customer_id', sa.String(36), nullable=True),
        sa.Column('group_id', sa.String(36), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('ssh_key_id', sa.String(36), nullable=True),
        sa.Column('last_seen', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('type',
                  sa.Enum('BAGET', 'CABRIO', 'ELM', 'OSA', 'CHIRON', 'UNKNOWN'),
                  nullable=False),
        sa.Column('update_to', sa.String(32), nullable=True),
        sa.Column('version', sa.String(32), nullable=True),
        sa.Column('max_cbt_get_blocks_bps', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('max_receiver_bps', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('max_parallel_disks', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['customer_id'], ['customer.id'],
                                name='agent_ibfk_1'),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'],
                                name='agent_ibfk_group'),
        sa.ForeignKeyConstraint(['ssh_key_id'], ['ssh_key.id'],
                                name='agent_ibfk_ssh_key'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'device',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('group_id', sa.String(36), nullable=True),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('last_agent_id', sa.String(36), nullable=True),
        sa.Column('cloud_overlay', sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['group.id'],
                                name='device_ibfk_1'),
        sa.ForeignKeyConstraint(['last_agent_id'], ['agent.id'],
                                name='device_ibfk_agent'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'backup',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('state', sa.String(256), nullable=True),
        sa.Column('created', sa.TIMESTAMP(), nullable=False),
        sa.Column('device_id', sa.String(36), nullable=True),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('lock_secret', sa.BigInteger(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'],
                                name='backup_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'failover',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('created', sa.TIMESTAMP(), nullable=False),
        sa.Column('backup_id', sa.String(36), nullable=True),
        sa.Column('port_id', sa.String(36), nullable=True),
        sa.Column('floating_ip', sa.String(36), nullable=True),
        sa.Column('instance_id', sa.String(36), nullable=True),
        sa.Column('tmp_snap_id', sa.String(36), nullable=True),
        sa.Column('container_id', sa.String(36), nullable=True),
        sa.Column('cloudsite_id', sa.String(36), nullable=True),
        sa.Column('connection_string', sa.TEXT(), nullable=True),
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('cpu', sa.Integer(), nullable=True),
        sa.Column('ram', sa.Integer(), nullable=True),
        sa.Column('image_id', sa.String(36), nullable=True),
        sa.Column('import_task_id', sa.String(36), nullable=True),
        sa.ForeignKeyConstraint(['backup_id'], ['backup.id'],
                                name='failover_ibfk_1'),
        sa.ForeignKeyConstraint(['cloudsite_id'], ['cloudsite.id'],
                                name='failover_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'drive',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('failover_id', sa.String(36), nullable=True),
        sa.Column('fatcow_id', sa.String(255), nullable=True),
        sa.Column('conn_str', sa.String(255), nullable=True),
        sa.Column('state', sa.Enum('PENDING', 'PREPARATION', 'PARTITIONING',
                                   'DISABLING_AGENT', 'P2V', 'READY',
                                   'DELETING', 'ERROR',
                                   'DISABLING_REPAIR_SCREEN',
                                   'FIXING_GPT_POSITION'), nullable=True),
        sa.Column('error_cause', sa.TEXT(), nullable=True),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('os_volume_id', sa.String(36), nullable=True),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('payload_connection_info', sa.TEXT(), nullable=True),
        sa.Column('payload_volume_id', sa.String(36), nullable=True),
        sa.Column('payload_volume_size', sa.Integer(), autoincrement=False,
                  nullable=True),
        sa.Column('project_id', sa.String(36), nullable=True),
        sa.Column('endpoint', sa.TEXT(), nullable=True),
        sa.Column('cloud_volume_id', sa.String(36), nullable=True),
        sa.Column('cloud_snapshot_id', sa.String(36), nullable=True),
        sa.Column('temp_snapshot_id', sa.String(36), nullable=True),
        sa.Column('drive_number', sa.Integer(), autoincrement=False,
                  nullable=True),
        sa.Column('cloud_volume_size', sa.Integer(), autoincrement=False,
                  nullable=True),
        sa.ForeignKeyConstraint(['cloud_volume_id'], ['cloud_volume.id'],
                                name='drive_ibfk_cloud_volume'),
        sa.ForeignKeyConstraint(['failover_id'], ['failover.id'],
                                name='drive_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'snapshot',
        sa.Column('state', sa.String(256), nullable=True),
        sa.Column('num', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(36), nullable=True),
        sa.Column('volume_id', sa.String(36), nullable=True),
        sa.Column('backup_id', sa.String(36), nullable=True),
        sa.Column('meta', sa.String(256), nullable=True),
        sa.Column('size', sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('type', sa.Enum('FULL', 'INCREMENTAL'), nullable=False),
        sa.Column('cloud_snapshot_id', sa.String(36), nullable=True),
        sa.Column('cloud_volume_id', sa.String(36), nullable=True),
        sa.Column('offset', sa.BigInteger(), autoincrement=False,
                  nullable=True),
        sa.Column('total_size', sa.BigInteger(), autoincrement=False,
                  nullable=False),
        sa.ForeignKeyConstraint(['backup_id'], ['backup.id'],
                                name='snapshot_ibfk_1'),
        sa.ForeignKeyConstraint(['cloud_volume_id'], ['cloud_volume.id'],
                                name='snapshot_ibfk_cloud_volume'),
        sa.PrimaryKeyConstraint('num'),
    )
    op.create_index(op.f('ix_snapshot_id'), 'snapshot', ['id'], unique=False)
    op.create_table(
        'snapshot_drive_association',
        sa.Column('snapshot_id', sa.String(36), nullable=True),
        sa.Column('drive_id', sa.String(36), nullable=True),
        sa.ForeignKeyConstraint(['drive_id'], ['drive.id'], ),
        sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'], )
    )
    op.create_table(
        'payload',
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('drive_id', sa.String(36), nullable=False),
        sa.Column('snapshot_id', sa.String(36), nullable=True),
        sa.Column('mountpoint', sa.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(['drive_id'], ['drive.id'],
                                name='payload_ibfk_1'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'],
                                name='payload_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'failover_script',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('failover_id', sa.String(36), nullable=False),
        sa.Column('script_id', sa.String(36), nullable=False),
        sa.Column('parameters', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['failover_id'], ['failover.id'],
                                name='failover_script_ibfk_1'),
        sa.ForeignKeyConstraint(['script_id'], ['script.id'],
                                name='failover_script_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'failback_device',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('device_id', sa.String(36), nullable=True),
        sa.Column('failback_id', sa.String(36), nullable=False),
        sa.Column('esxi_host_id', sa.String(36), nullable=True),
        sa.Column('esxi_datastore_id', sa.String(36), nullable=True),
        sa.Column('name', sa.String(256), nullable=False),
        sa.Column('hardware', sa.TEXT(), nullable=False),
        sa.Column('sync_status',
                  sa.Enum('IDLE', 'SYNC', 'READY', 'ERROR', 'CANCEL'),
                  nullable=False),
        sa.Column('update_time', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('progress', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('cloud_server_id', sa.String(36), nullable=True),
        sa.ForeignKeyConstraint(['device_id'], ['device.id'],
                                name='failback_device_ibfk_1'),
        sa.ForeignKeyConstraint(['esxi_datastore_id'], ['esxi_datastore.id'],
                                name='failback_device_ibfk_2'),
        sa.ForeignKeyConstraint(['esxi_host_id'], ['esxi_host.id'],
                                name='failback_device_ibfk_3'),
        sa.ForeignKeyConstraint(['failback_id'], ['failback.id'],
                                name='failback_device_ibfk_4'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'failback_snapshot',
        sa.Column('deleted_at', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('id', sa.String(36), nullable=False),
        sa.Column('drive_id', sa.String(36), nullable=False),
        sa.Column('snapshot_id', sa.String(36), nullable=True),
        sa.Column('type', sa.Enum('BACKUP', 'FATCOW', 'CLOUD'), default='CLOUD',
                  nullable=False),
        sa.Column('generation', sa.Integer(), autoincrement=False,
                  nullable=False),
        sa.Column('failback_device_id', sa.String(36), nullable=False),
        sa.Column('drive_size', sa.BigInteger(), autoincrement=False,
                  nullable=False),
        sa.Column('meta', sa.TEXT(), nullable=True),
        sa.Column('origin_drive_id', sa.String(36), nullable=False),
        sa.Column('cloud_snapshot_id', sa.String(36), nullable=True),
        sa.Column('cloud_volume_id', sa.String(36), nullable=True),
        sa.ForeignKeyConstraint(['drive_id'], ['drive.id'],
                                name='failback_snapshot_ibfk_1'),
        sa.ForeignKeyConstraint(['failback_device_id'], ['failback_device.id'],
                                name='fk_fb_device_id'),
        sa.ForeignKeyConstraint(['origin_drive_id'], ['drive.id'],
                                name='fb_snapshot_ibfk1'),
        sa.ForeignKeyConstraint(['snapshot_id'], ['snapshot.id'],
                                name='failback_snapshot_ibfk_2'),
        sa.PrimaryKeyConstraint('id'),
    )
