""""“cloudsite_timestamps”"

Revision ID: e8a9705b210d
Revises: 55739f28884a
Create Date: 2017-09-01 13:47:24.174108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8a9705b210d'
down_revision = '55739f28884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsite', sa.Column('device_timestamps', sa.TEXT(),
                                         nullable=True))
    op.add_column('cloudsite', sa.Column('timestamp', sa.Integer(),
                                         nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloudsite', 'timestamp')
    op.drop_column('cloudsite', 'device_timestamps')
    # ### end Alembic commands ###
