""""device_cloud_overlay"

Revision ID: e8d5e21e2f8a
Revises: 521b81e79a85
Create Date: 2019-01-21 10:03:37.719010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8d5e21e2f8a'
down_revision = '521b81e79a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('cloud_overlay', sa.TEXT(),
                                      nullable=False))
    op.add_column('cloud_agent', sa.Column('cloud_config', sa.TEXT(),
                                           nullable=True))
    dt = sa.sql.table('device',  sa.sql.column('cloud_overlay', sa.TEXT()))
    op.execute(dt.update().values(cloud_overlay='{}'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'cloud_overlay')
    op.drop_column('cloud_agent', 'cloud_config')
    # ### end Alembic commands ###
