""""“partner_password_removed”"

Revision ID: eb2dc922a243
Revises: 50339b903913
Create Date: 2017-06-08 14:45:12.408738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eb2dc922a243'
down_revision = '50339b903913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('password', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###
