""""cloud_config_for_cs"

Revision ID: fd808cf92f7b
Revises: edad38e1dd89
Create Date: 2018-11-30 11:53:35.924292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd808cf92f7b'
down_revision = 'edad38e1dd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudsite', sa.Column('cloud_config', sa.TEXT(),
                                         nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloudsite', 'cloud_config')
    # ### end Alembic commands ###
