""""profiling_tokens"

Revision ID: 9459cfa84bec
Revises: c333baae923d
Create Date: 2022-10-24 18:53:27.311317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9459cfa84bec'
down_revision = 'c333baae923d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'profiling_token',
        sa.Column('deleted_at', sa.Integer(), nullable=False),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.Integer(), nullable=False),
        sa.Column('organization_id', sa.String(length=36), nullable=False),
        sa.Column('token', sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('organization_id', 'deleted_at',
                            name='organization_deleted_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiling_token')
    # ### end Alembic commands ###
