""""organization_bi_table"

Revision ID: ac24cf000c44
Revises: 08e49b457ebb
Create Date: 2022-07-15 10:10:45.279797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac24cf000c44"
down_revision = "08e49b457ebb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization_bi",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.Enum("AWS_RAW_EXPORT", "AZURE_RAW_EXPORT"),
                  nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("last_run", sa.Integer(), nullable=False),
        sa.Column("next_run", sa.Integer(), nullable=False),
        sa.Column("last_completed", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "QUEUED",
                "RUNNING",
                "FAILED",
                "SUCCESS",
            ),
            nullable=False,
        ),
        sa.Column("last_status_error", sa.TEXT, nullable=True),
        sa.Column("meta", sa.TEXT(), nullable=True),
        sa.Column("deleted_at", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "organization_id",
            "name",
            "deleted_at",
            name="uc_organization_id_name_deleted_at",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("organization_bi")
    # ### end Alembic commands ###
