ARG BUILDTAG=build
FROM bi_exporter:${BUILDTAG}

COPY bi_exporter/test-requirements.txt bi_exporter/run_tests.py bi_exporter/.pylintrc bi_exporter/
RUN pip install --no-cache-dir -r bi_exporter/test-requirements.txt
