ARG BUILDTAG=build
FROM auth:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY auth_server/tests ./tests
