"""Initial structure

Revision ID: 97c682297e16
Revises:
Create Date: 2021-09-15 13:15:22.185450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c682297e16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.Column('client_key', sa.String(length=36), nullable=False),
    sa.Column('shared_secret', sa.Text(), nullable=False),
    sa.Column('extra_payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_key', 'deleted_at', name='uc_client_key_deleted_at')
    )
    op.create_table('user_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.Column('jira_account_id', sa.String(length=128), nullable=False),
    sa.Column('secret', sa.String(length=36), nullable=False),
    sa.Column('auth_user_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jira_account_id', 'deleted_at', name='uc_jira_account_id_deleted_at'),
    sa.UniqueConstraint('secret', 'deleted_at', name='uc_secret_deleted_at')
    )
    op.create_table('organization_assignment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('app_installation_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['app_installation_id'], ['app_installation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'app_installation_id', 'deleted_at', name='uc_org_id_app_inst_id_del_at')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_assignment')
    op.drop_table('user_assignment')
    op.drop_table('app_installation')
    # ### end Alembic commands ###
