ARG BUILDTAG=build
FROM slacker:${BUILDTAG}

COPY optscale_client/slacker_client optscale_client/slacker_client
COPY slacker/test-requirements.txt slacker/.pylintrc slacker/.noserc slacker/.coveragerc ./slacker/
COPY slacker/slacker_server/tests slacker/slacker_server/tests
RUN pip install --no-cache-dir -r slacker/test-requirements.txt
