ARG BUILDTAG=build
FROM slacker:${BUILDTAG}

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
COPY slacker_server/tests slacker_server/tests
RUN pip install --no-cache-dir -r test-requirements.txt
