export const FIELD_NAMES = Object.freeze({
  TASK: "task",
  DATA_SOURCE: "dataSource",
  REGION: "region",
  INSTANCE_TYPE: "instanceType",
  IMAGE: "image",
  VIRTUAL_ENVIRONMENT_PATH: "virtualEnvironmentPath",
  USE_SPOT_INSTANCES: "useSpotInstances",
  MAX_SPOT_ATTEMPTS: "maxSpotAttempts",
  MAX_SPOT_COST_PER_HOUR: "maxSpotCostPerHour",
  HYPERPARAMETERS: "hyperparameters",
  CODE_TO_EXECUTE: "codeToExecute",
  MAX_BUDGET_CHECKBOX: "maxBudgetCheckbox",
  MAX_BUDGET_VALUE: "maxBudgetValue",
  REACHED_GOALS_CHECKBOX: "reachedGoalsCheckbox",
  MAX_DURATION_CHECKBOX: "maxDurationCheckbox",
  MAX_DURATION_VALUE: "maxDurationValue",
});
