ARG BUILDTAG=build
FROM metroculus_api:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt
COPY metroculus_api/tests ./tests
