ARG BUILDTAG=build
FROM ngui:${BUILDTAG}

WORKDIR "/usr/src/app/ui"
USER root
RUN npm install -g pnpm@8.11.0
RUN mv .disabled.eslintrc.cjs .eslintrc.cjs 
RUN pnpm install --frozen-lockfile --ignore-scripts