""""user_team_id"

Revision ID: 54f5b1854a44
Revises: 6edf443cadf7
Create Date: 2021-04-19 12:24:57.945216

"""
import uuid
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import table
from sqlalchemy import String, select, update, Column


# revision identifiers, used by Alembic.
revision = '54f5b1854a44'
down_revision = '6edf443cadf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('slack_team_id', sa.String(length=160),
                                    nullable=False))
    bind = op.get_bind()
    session = Session(bind=bind)
    try:
        users_table = table(
            'user',
            Column('slack_user_id', String(160)),
            Column('slack_team_id', String(160))
        )
        installations_table = table(
            'slack_installations',
            Column('team_id', String(160)),
            Column('user_id', String(160))
        )
        stmt = select([installations_table])
        installations = session.execute(stmt)
        team_users_map = {}
        for installation in installations:
            team_id = installation.team_id
            if team_id not in team_users_map:
                team_users_map[team_id] = set()
            team_users_map[team_id].add(installation.user_id)
        for team_id, user_ids in team_users_map.items():
            update_stmt = update(
                users_table
            ).values(
                slack_team_id=team_id,
            ).where(
                users_table.c.slack_user_id.in_(list(user_ids))
            )
            session.execute(update_stmt)
        session.commit()
    except Exception:
        session.rollback()
        op.drop_column('user', 'slack_team_id')
        raise
    finally:
        session.close()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'slack_team_id')
    # ### end Alembic commands ###
