""""fix_columns"

Revision ID: bef11b8e816d
Revises: 54f5b1854a44
Create Date: 2024-05-16 04:30:21.110346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bef11b8e816d'
down_revision = '54f5b1854a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_bots',
                  sa.Column('bot_refresh_token', sa.String(length=200),
                            nullable=True))
    op.add_column('slack_bots',
                  sa.Column('bot_token_expires_at', sa.DateTime(),
                            nullable=True))
    op.alter_column('slack_bots', 'client_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('slack_bots', 'app_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('slack_bots', 'enterprise_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'enterprise_name',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'team_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'team_name',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_token',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_user_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_scopes',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=1000),
                    existing_nullable=True)
    op.add_column('slack_installations',
                  sa.Column('bot_refresh_token', sa.String(length=200),
                            nullable=True))
    op.add_column('slack_installations',
                  sa.Column('bot_token_expires_at', sa.DateTime(),
                            nullable=True))
    op.add_column('slack_installations',
                  sa.Column('user_refresh_token', sa.String(length=200),
                            nullable=True))
    op.add_column('slack_installations',
                  sa.Column('user_token_expires_at', sa.DateTime(),
                            nullable=True))
    op.alter_column('slack_installations', 'client_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'app_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'enterprise_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'enterprise_name',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'enterprise_url',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'team_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'team_name',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_token',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_user_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_scopes',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=1000),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'user_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'user_token',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'user_scopes',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=1000),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_url',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel_id',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations',
                    'incoming_webhook_configuration_url',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'token_type',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=32),
                    existing_nullable=True)
    op.alter_column('slack_oauth_states', 'state',
                    existing_type=mysql.VARCHAR(length=160),
                    type_=sa.String(length=200),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slack_oauth_states', 'state',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'token_type',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations',
                    'incoming_webhook_configuration_url',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel_id',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_channel',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'incoming_webhook_url',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'user_scopes',
                    existing_type=sa.String(length=1000),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'user_token',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'user_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'bot_scopes',
                    existing_type=sa.String(length=1000),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_user_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'bot_token',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'team_name',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'team_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'enterprise_url',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'enterprise_name',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'enterprise_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_installations', 'app_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.alter_column('slack_installations', 'client_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.drop_column('slack_installations', 'user_token_expires_at')
    op.drop_column('slack_installations', 'user_refresh_token')
    op.drop_column('slack_installations', 'bot_token_expires_at')
    op.drop_column('slack_installations', 'bot_refresh_token')
    op.alter_column('slack_bots', 'bot_scopes',
                    existing_type=sa.String(length=1000),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_user_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'bot_token',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'team_name',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'team_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'enterprise_name',
                    existing_type=sa.String(length=200),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'enterprise_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=True)
    op.alter_column('slack_bots', 'app_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.alter_column('slack_bots', 'client_id',
                    existing_type=sa.String(length=32),
                    type_=mysql.VARCHAR(length=160),
                    existing_nullable=False)
    op.drop_column('slack_bots', 'bot_token_expires_at')
    op.drop_column('slack_bots', 'bot_refresh_token')
    # ### end Alembic commands ###
