export const ALERT_TYPES = Object.freeze({
  DATA_SOURCES_ARE_PROCESSING: 2,
  DATA_SOURCES_PROCEEDED: 3,
  OPEN_SOURCE_ANNOUNCEMENT: 4,
  INACTIVE_ORGANIZATION: 5,
});

export const IS_EXISTING_USER = "isExistingUser";
