apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: {{ .Release.Namespace }}
data:
  .dockercfg: >-
    ewogICJodHRwczovL2luZGV4LmRvY2tlci5pby92Mi8iOiB7CiAgICAidXNlcm5hbWUiOiAiZG9ja2VydGVzc2VsbCIsCiAgICAicGFzc3dvcmQiOiAiaXppWXx8Uzh2enVNQ0k3cSMxfHAiCiAgfQp9
type: kubernetes.io/dockercfg

