{{- if .Values.dockerhub_dockercfg }}
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-creds
  namespace: {{ .Release.Namespace }}
data:
  .dockercfg: {{ .Values.dockerhub_dockercfg }}
type: kubernetes.io/dockercfg
{{- end }}
