{{- $config := .Values.grafana -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ $config.service.type }}
  ports:
    - nodePort: {{ $config.service.externalPort }}
      port: {{ $config.service.internalPort }}
      targetPort: {{ $config.service.internalPort }}
      protocol: TCP
      name: {{ $config.service.name }}
  selector:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.name }}
      release: {{ .Release.Name }}
  serviceName: {{ $config.service.name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
{{- if .Values.elk.enabled }}
{{ include "wait_for_elk" . | indent 6 }}
{{- end }}
{{ include "wait_for_service" .Values.influxdb | indent 6 }}
      containers:
      - name: {{ $config.name }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $config.image.pullPolicy }}
        ports:
        - containerPort: {{ $config.internalPort }}
        env:
        - name: IMAGE_ID
          value: {{ $config.image.id }}
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_USERS_AUTO_ASSIGN_ORG
          value: "true"
        - name: GF_USERS_AUTO_ASSIGN_ORG_ROLE
          value: "Editor"
        - name: GF_AUTH_PROXY_ENABLED
          value: "true"
        - name: GF_AUTH_PROXY_HEADER_NAME
          value: "X-WEBAUTH-USER"
        - name: GF_AUTH_PROXY_HEADER_PROPERTY
          value: "username"
        - name: GF_AUTH_PROXY_AUTO_SIGN_UP
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_DISABLE_SIGNOUT_MENU
          value: "true"
        - name: GF_AUTH_BASIC_ENABLED
          value: "false"
      - name: "{{ $config.grafana_nginx.name }}"
        image: "{{ $config.grafana_nginx.image.repository }}:{{ $config.grafana_nginx.image.tag }}"
        imagePullPolicy: {{ $config.grafana_nginx.image.pullPolicy }}
        ports:
        - containerPort: {{ $config.service.internalPort }}
{{ include "ready_probe" $config | indent 8 }}
      volumes:
      - name: shared
        emptyDir: {}
