{{- $config := .Values.ohsu -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $config.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ $config.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
{{ include "wait_for_service" .Values.etcd | indent 6 }}
      containers:
      - name: {{ $config.name }}
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $config.image.pullPolicy }}
        env:
        - name: IMAGE_ID
          value: {{ $config.image.id }}
        - name: HX_ETCD_HOST
          value: {{ .Values.etcd.service.name }}
        - name: HX_ETCD_PORT
          value: {{ .Values.etcd.service.externalPort | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  type: {{ $config.service.type }}
  ports:
{{- range untilStep 30180 30280 1 }}
    - port: {{ . }}
      targetPort: {{ . }}
      containerPort: {{ . }}
      nodePort: {{ . }}
      name: shs-port-{{ . }}
{{- end }}
    - port: 80
      targetPort: 9377
      protocol: TCP
      name: {{ $config.service.name }}
  selector:
    app: {{ $config.name }}
    release: {{ .Release.Name }}