{{- $config := .Values.thanos_storegateway -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
spec:
  type: {{ $config.service.type }}
  ports:
    - port: {{ $config.service.httpExternalPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $config.service.grpcExternalPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $config.name }}
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ $config.name }}
spec:
  storageClassName: {{ $config.name }}
  capacity:
    storage: {{ $config.dataSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/acura/{{ $config.name }}"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $config.name }}-claim
spec:
  storageClassName: {{ $config.name }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $config.dataSize }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $config.service.name }}
  labels:
    app: {{ $config.name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ $config.replicaCount }}
  podManagementPolicy: OrderedReady
  serviceName: {{ $config.service.name }}
  selector:
    matchLabels:
      app: {{ $config.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $config.name }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
{{- if .Values.elk.enabled }}
{{ include "wait_for_elk" . | indent 6 }}
{{- end }}
{{ include "wait_for_service" .Values.minio | indent 6 }}
      containers:
        - name: storegateway
          image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
          imagePullPolicy: "{{ $config.image.pullPolicy }}"
          command:
            - thanos
          args:
            - store
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --objstore.config-file=/var/thanos/config/thanos_conf.yaml
            - --data-dir=/var/thanos/data
          ports:
            - containerPort: 10901
              name: grpc
              protocol: TCP
            - containerPort: 10902
              name: http
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - name: data
              mountPath: /var/thanos/data
            - name: config
              mountPath: /var/thanos/config
              readOnly: true
      volumes:
        - name: config
          secret:
            secretName: thanos-secret
            items:
              - key: thanos_conf.yaml
                path: thanos_conf.yaml
        - name: data
          persistentVolumeClaim:
            claimName: {{ $config.name }}-claim
