ARG BUILDTAG=build
FROM trapper_worker:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

COPY trapper/test-requirements.txt trapper/.pylintrc trapper/.noserc trapper/.coveragerc ./trapper/
RUN pip install --no-cache-dir -r trapper/test-requirements.txt
