ARG BUILDTAG=build
ARG IMAGE=risp_worker
FROM ${IMAGE}:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

ADD risp/risp_worker/tests risp/risp_worker/tests
COPY risp/test-requirements.txt risp/.pylintrc risp/run_tests.py risp/run_test.sh ./risp/
RUN pip install --no-cache-dir -r risp/test-requirements.txt
