export const GET_ORGANIZATION_FEATURES = "GET_ORGANIZATION_FEATURES";
export const SET_ORGANIZATION_FEATURES = "SET_ORGANIZATION_FEATURES";
export const UPDATE_ORGANIZATION_PERSPECTIVES = "UPDATE_ORGANIZATION_PERSPECTIVES";

export const SET_ORGANIZATION_PERSPECTIVES = "SET_ORGANIZATION_PERSPECTIVES";
export const GET_ORGANIZATION_PERSPECTIVES = "GET_ORGANIZATION_PERSPECTIVES";

export const GET_ORGANIZATION_THEME_SETTINGS = "GET_ORGANIZATION_THEME_SETTINGS";
export const SET_ORGANIZATION_THEME_SETTINGS = "SET_ORGANIZATION_THEME_SETTINGS";
export const UPDATE_ORGANIZATION_THEME_SETTINGS = "UPDATE_ORGANIZATION_THEME_SETTINGS";

export const GET_ORGANIZATION_OPTIONS = "GET_ORGANIZATION_OPTIONS";
export const SET_ORGANIZATION_OPTIONS = "SET_ORGANIZATION_OPTIONS";

export const GET_ORGANIZATION_OPTION = "GET_ORGANIZATION_OPTION";
export const DELETE_ORGANIZATION_OPTION = "DELETE_ORGANIZATION_OPTION";
export const UPDATE_ORGANIZATION_OPTION = "UPDATE_ORGANIZATION_OPTION";
export const CREATE_ORGANIZATION_OPTION = "CREATE_ORGANIZATION_OPTION";
export const SET_ORGANIZATION_OPTION = "SET_ORGANIZATION_OPTION";

export const GET_DATA_SOURCES = "GET_DATA_SOURCES";
export const SET_DATA_SOURCES = "SET_DATA_SOURCES";

export const CREATE_DATA_SOURCE = "CREATE_DATA_SOURCE";
export const DELETE_DATA_SOURCE = "DELETE_DATA_SOURCE";
export const UPDATE_DATA_SOURCE = "UPDATE_DATA_SOURCE";

export const GET_POOL = "GET_POOL";
export const SET_POOL = "SET_POOL";

export const GET_DATA_SOURCE_DETAILS = "GET_DATA_SOURCE_DETAILS";
export const SET_DATA_SOURCE_DETAILS = "SET_DATA_SOURCE_DETAILS";

export const CREATE_POOL = "CREATE_POOL";

export const CREATE_ORGANIZATION = "CREATE_ORGANIZATION";

export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";

export const GET_ORGANIZATION_CONSTRAINTS = "GET_ORGANIZATION_CONSTRAINTS";
export const SET_ORGANIZATION_CONSTRAINTS = "SET_ORGANIZATION_CONSTRAINTS";
export const CREATE_ORGANIZATION_CONSTRAINT = "CREATE_ORGANIZATION_CONSTRAINT";
export const GET_ORGANIZATION_CONSTRAINT = "GET_ORGANIZATION_CONSTRAINT";
export const SET_ORGANIZATION_CONSTRAINT = "SET_ORGANIZATION_CONSTRAINT";
export const DELETE_ORGANIZATION_CONSTRAINT = "DELETE_ORGANIZATION_CONSTRAINT";
export const UPDATE_ORGANIZATION_CONSTRAINT = "UPDATE_ORGANIZATION_CONSTRAINT";

export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";

export const GET_ORGANIZATIONS_OVERVIEW = "GET_ORGANIZATIONS_OVERVIEW";
export const SET_ORGANIZATIONS_OVERVIEW = "SET_ORGANIZATIONS_OVERVIEW";

export const UPDATE_POOL = "UPDATE_POOL";

export const DELETE_POOL = "DELETE_POOL";

export const GET_POOLS_EXPENSES = "GET_POOLS_EXPENSES";
export const SET_COST_EXPLORER_POOL_EXPENSES = "SET_COST_EXPLORER_POOL_EXPENSES";
export const SET_POOL_EXPENSES_BREAKDOWN = "SET_POOL_EXPENSES_BREAKDOWN";

export const CREATE_POOL_EXPENSES_EXPORT = "CREATE_POOL_EXPENSES_EXPORT";
export const DELETE_POOL_EXPENSES_EXPORT = "DELETE_POOL_EXPENSES_EXPORT";
export const UPDATE_POOL_EXPENSES_EXPORT = "UPDATE_POOL_EXPENSES_EXPORT";

export const GET_CLOUDS_EXPENSES = "GET_CLOUDS_EXPENSES";
export const SET_CLOUDS_EXPENSES = "SET_CLOUDS_EXPENSES";

export const GET_EMPLOYEES_EXPENSES = "GET_EMPLOYEES_EXPENSES";
export const SET_EMPLOYEES_EXPENSES = "SET_EMPLOYEES_EXPENSES";

export const GET_REGION_EXPENSES = "GET_REGION_EXPENSES";
export const SET_REGION_EXPENSES = "SET_REGION_EXPENSES";

export const GET_TRAFFIC_EXPENSES = "GET_TRAFFIC_EXPENSES";
export const SET_TRAFFIC_EXPENSES = "SET_TRAFFIC_EXPENSES";

export const UPLOAD_CLOUD_REPORT = "UPLOAD_CLOUD_REPORT";

export const UPLOAD_CODE_REPORT = "UPLOAD_CODE_REPORT";

export const SUBMIT_FOR_AUDIT = "SUBMIT_FOR_AUDIT";

export const GET_INVITATION = "GET_INVITATION";
export const SET_INVITATION = "SET_INVITATION";
export const UPDATE_INVITATION = "UPDATE_INVITATION";
export const CREATE_INVITATIONS = "CREATE_INVITATIONS";

export const GET_INVITATIONS = "GET_INVITATIONS";
export const SET_INVITATIONS = "SET_INVITATIONS";

export const GET_SPLIT_RESOURCES = "GET_SPLIT_RESOURCES";
export const SET_SPLIT_RESOURCES = "SET_SPLIT_RESOURCES";

export const GET_AVAILABLE_POOLS = "GET_AVAILABLE_POOLS";
export const SET_AVAILABLE_POOLS = "SET_AVAILABLE_POOLS";

export const GET_POOL_OWNERS = "GET_POOL_OWNERS";
export const SET_POOL_OWNERS = "SET_POOL_OWNERS";

export const GET_AUTHORIZED_EMPLOYEES = "GET_AUTHORIZED_EMPLOYEES";
export const SET_AUTHORIZED_EMPLOYEES = "SET_AUTHORIZED_EMPLOYEES";

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const SET_CURRENT_EMPLOYEE = "SET_CURRENT_EMPLOYEE";
export const GET_CURRENT_EMPLOYEE = "GET_CURRENT_EMPLOYEE";

export const ASSIGNMENT_REQUEST_UPDATE = "ASSIGNMENT_REQUEST_UPDATE";

export const GET_ORGANIZATION_EXPENSES = "GET_ORGANIZATION_EXPENSES";
export const SET_ORGANIZATION_EXPENSES = "SET_ORGANIZATION_EXPENSES";

export const GET_RAW_EXPENSES = "GET_RAW_EXPENSES";
export const SET_RAW_EXPENSES = "SET_RAW_EXPENSES";

export const GET_CLEAN_EXPENSES = "GET_CLEAN_EXPENSES";
export const SET_CLEAN_EXPENSES = "SET_CLEAN_EXPENSES";

export const GET_EXPENSES_SUMMARY = "GET_EXPENSES_SUMMARY";
export const SET_EXPENSES_SUMMARY = "SET_EXPENSES_SUMMARY";

export const GET_AVAILABLE_FILTERS = "GET_AVAILABLE_FILTERS";
export const SET_AVAILABLE_FILTERS = "SET_AVAILABLE_FILTERS";

export const GET_RESOURCE_COUNT_BREAKDOWN = "GET_RESOURCE_COUNT_BREAKDOWN";
export const SET_RESOURCE_COUNT_BREAKDOWN = "SET_RESOURCE_COUNT_BREAKDOWN";

export const GET_TAGS_BREAKDOWN = "GET_TAGS_BREAKDOWN";
export const SET_TAGS_BREAKDOWN = "SET_TAGS_BREAKDOWN";

export const CREATE_ASSIGNMENT_RULE = "CREATE_ASSIGNMENT_RULE";

export const GET_ASSIGNMENT_RULES = "GET_ASSIGNMENT_RULES";
export const SET_ASSIGNMENT_RULES = "SET_ASSIGNMENT_RULES";

export const GET_K8S_RIGHTSIZING = "GET_K8S_RIGHTSIZING";
export const SET_K8S_RIGHTSIZING = "SET_K8S_RIGHTSIZING";

export const DELETE_ASSIGNMENT_RULE = "DELETE_ASSIGNMENT_RULE";

export const GET_ASSIGNMENT_RULE = "GET_ASSIGNMENT_RULE";
export const SET_ASSIGNMENT_RULE = "SET_ASSIGNMENT_RULE";

export const UPDATE_ASSIGNMENT_RULE = "UPDATE_ASSIGNMENT_RULE";
export const UPDATE_ASSIGNMENT_RULE_PRIORITY = "UPDATE_ASSIGNMENT_RULE_PRIORITY";

export const GET_RESOURCE = "GET_RESOURCE";
export const SET_RESOURCE = "SET_RESOURCE";
export const UPDATE_RESOURCE = "UPDATE_RESOURCE";

export const CREATE_POOL_POLICY = "CREATE_POOL_POLICY";
export const UPDATE_POOL_POLICY_LIMIT = "UPDATE_POOL_POLICY_LIMIT";
export const UPDATE_POOL_POLICY_ACTIVITY = "UPDATE_POOL_POLICY_ACTIVITY";
export const GET_POOL_POLICIES = "GET_POOL_POLICIES";
export const SET_POOL_POLICIES = "SET_POOL_POLICIES";
export const SET_POOL_POLICY = "SET_POOL_POLICY";

export const CREATE_GLOBAL_POOL_POLICY = "CREATE_GLOBAL_POOL_POLICY";
export const UPDATE_GLOBAL_POOL_POLICY = "UPDATE_GLOBAL_POOL_POLICY";
export const UPDATE_GLOBAL_POOL_POLICY_LIMIT = "UPDATE_GLOBAL_POOL_POLICY_LIMIT";
export const UPDATE_GLOBAL_POOL_POLICY_ACTIVITY = "UPDATE_GLOBAL_POOL_POLICY_ACTIVITY";

export const UPDATE_GLOBAL_RESOURCE_CONSTRAINT = "UPDATE_GLOBAL_RESOURCE_CONSTRAINT";
export const UPDATE_GLOBAL_RESOURCE_CONSTRAINT_LIMIT = "UPDATE_GLOBAL_RESOURCE_CONSTRAINT_LIMIT";
export const DELETE_GLOBAL_RESOURCE_CONSTRAINT = "DELETE_GLOBAL_RESOURCE_CONSTRAINT";

export const CREATE_TOTAL_EXPENSE_LIMIT_RESOURCE_CONSTRAINT = "CREATE_TOTAL_EXPENSE_LIMIT_RESOURCE_CONSTRAINT";
export const CREATE_DAILY_EXPENSE_LIMIT_RESOURCE_CONSTRAINT = "CREATE_DAILY_EXPENSE_LIMIT_RESOURCE_CONSTRAINT";
export const CREATE_TTL_RESOURCE_CONSTRAINT = "CREATE_TTL_RESOURCE_CONSTRAINT";
export const UPDATE_TTL_RESOURCE_CONSTRAINT = "UPDATE_TTL_RESOURCE_CONSTRAINT";
export const UPDATE_TOTAL_EXPENSE_LIMIT_RESOURCE_CONSTRAINT = "UPDATE_TOTAL_EXPENSE_LIMIT_RESOURCE_CONSTRAINT";
export const UPDATE_DAILY_EXPENSE_LIMIT_RESOURCE_CONSTRAINT = "UPDATE_DAILY_EXPENSE_LIMIT_RESOURCE_CONSTRAINT";
export const DELETE_RESOURCE_CONSTRAINT = "DELETE_RESOURCE_CONSTRAINT";
export const SET_RESOURCE_CONSTRAINT = "SET_RESOURCE_CONSTRAINT";

export const GET_RESOURCE_LIMIT_HITS = "GET_RESOURCE_LIMIT_HITS";
export const SET_RESOURCE_LIMIT_HITS = "SET_RESOURCE_LIMIT_HITS";

export const GET_OPTIMIZATIONS = "GET_OPTIMIZATIONS";
export const SET_OPTIMIZATIONS = "SET_OPTIMIZATIONS";
export const UPDATE_OPTIMIZATIONS = "UPDATE_OPTIMIZATIONS";

export const GET_OPTIMIZATION_DETAILS = "GET_OPTIMIZATION_DETAILS";
export const SET_OPTIMIZATION_DETAILS = "SET_OPTIMIZATION_DETAILS";

export const GET_ML_OPTIMIZATION_DETAILS = "GET_ML_OPTIMIZATION_DETAILS";
export const SET_ML_OPTIMIZATION_DETAILS = "SET_ML_OPTIMIZATION_DETAILS";

export const GET_OPTIMIZATIONS_OVERVIEW = "GET_OPTIMIZATIONS_OVERVIEW";
export const SET_OPTIMIZATIONS_OVERVIEW = "SET_OPTIMIZATIONS_OVERVIEW";

export const SET_OPTIMIZATION_OPTIONS = "SET_OPTIMIZATION_OPTIONS";
export const GET_OPTIMIZATION_OPTIONS = "GET_OPTIMIZATION_OPTIONS";
export const UPDATE_OPTIMIZATION_OPTIONS = "UPDATE_OPTIMIZATION_OPTIONS";

export const GET_LIVE_DEMO = "GET_LIVE_DEMO";
export const SET_LIVE_DEMO = "SET_LIVE_DEMO";
export const CREATE_LIVE_DEMO = "CREATE_LIVE_DEMO";

export const GET_TTL_ANALYSIS = "GET_TTL_ANALYSIS";
export const SET_TTL_ANALYSIS = "SET_TTL_ANALYSIS";

export const APPLY_ASSIGNMENT_RULES = "APPLY_ASSIGNMENT_RULES";

export const UPDATE_RESOURCE_VISIBILITY = "UPDATE_RESOURCE_VISIBILITY";

export const GET_FINOPS_CHECKLIST = "GET_FINOPS_CHECKLIST";
export const SET_FINOPS_CHECKLIST = "SET_FINOPS_CHECKLIST";
export const UPDATE_FINOPS_CHECKLIST = "UPDATE_FINOPS_CHECKLIST";

export const GET_TECHNICAL_AUDIT = "GET_TECHNICAL_AUDIT";
export const SET_TECHNICAL_AUDIT = "SET_TECHNICAL_AUDIT";
export const UPDATE_TECHNICAL_AUDIT = "UPDATE_TECHNICAL_AUDIT";

export const GET_RECOMMENDATIONS_DOWNLOAD_OPTIONS = "GET_RECOMMENDATIONS_DOWNLOAD_OPTIONS";
export const SET_RECOMMENDATIONS_DOWNLOAD_OPTIONS = "SET_RECOMMENDATIONS_DOWNLOAD_OPTIONS";

export const GET_CLUSTER_TYPES = "GET_CLUSTER_TYPES";
export const SET_CLUSTER_TYPES = "SET_CLUSTER_TYPES";
export const CREATE_CLUSTER_TYPE = "CREATE_CLUSTER_TYPE";
export const DELETE_CLUSTER_TYPE = "DELETE_CLUSTER_TYPE";
export const UPDATE_CLUSTER_TYPE_PRIORITY = "UPDATE_CLUSTER_TYPE_PRIORITY";
export const APPLY_CLUSTER_TYPES = "APPLY_CLUSTER_TYPES";

export const GET_ENVIRONMENTS = "GET_ENVIRONMENTS";
export const SET_ENVIRONMENTS = "SET_ENVIRONMENTS";
export const CREATE_ENVIRONMENT = "CREATE_ENVIRONMENT";
export const DELETE_ENVIRONMENT = "DELETE_ENVIRONMENT";
export const UPDATE_ENVIRONMENT_ACTIVITY = "UPDATE_ENVIRONMENT_ACTIVITY";
export const UPDATE_ENVIRONMENT_SSH_REQUIREMENT = "UPDATE_ENVIRONMENT_SSH_REQUIREMENT";
export const UPDATE_ENVIRONMENT_PROPERTY = "UPDATE_ENVIRONMENT_PROPERTY";
export const GET_ENVIRONMENT_BOOKINGS = "GET_ENVIRONMENT_BOOKINGS";
export const SET_ENVIRONMENT_BOOKINGS = "SET_ENVIRONMENT_BOOKINGS";

export const GET_WEBHOOKS = "GET_WEBHOOKS";
export const SET_WEBHOOKS = "SET_WEBHOOKS";
export const CREATE_WEBHOOK = "CREATE_WEBHOOK";
export const UPDATE_WEBHOOK = "UPDATE_WEBHOOK";
export const DELETE_WEBHOOK = "DELETE_WEBHOOK";

export const GET_SSH_KEYS = "GET_SSH_KEYS";
export const SET_SSH_KEYS = "SET_SSH_KEYS";
export const CREATE_SSH_KEY = "CREATE_SSH_KEY";
export const UPDATE_SSH_KEY = "UPDATE_SSH_KEY";
export const DELETE_SSH_KEY = "DELETE_SSH_KEY";

export const GET_DATA_SOURCE_NODES = "GET_DATA_SOURCE_NODES";
export const SET_DATA_SOURCE_NODES = "SET_DATA_SOURCE_NODES";

export const GET_RESOURCE_METRICS = "GET_RESOURCE_METRICS";
export const SET_RESOURCE_METRICS = "SET_RESOURCE_METRICS";

export const GET_RESOURCE_COST_MODEL = "GET_RESOURCE_COST_MODEL";
export const SET_RESOURCE_COST_MODEL = "SET_RESOURCE_COST_MODEL";
export const UPDATE_RESOURCE_COST_MODEL = "UPDATE_RESOURCE_COST_MODEL";

export const GET_DATASOURCE_SKUS = "GET_DATASOURCE_SKUS";
export const SET_DATASOURCE_SKUS = "SET_DATASOURCE_SKUS";
export const UPDATE_DATASOURCE_SKU = "UPDATE_DATASOURCE_SKU";

export const MARK_RESOURCES_AS_ENVIRONMENTS = "MARK_RESOURCES_AS_ENVIRONMENTS";

export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const DELETE_BOOKING = "DELETE_BOOKING";

export const BOOK_ENVIRONMENT = "BOOK_ENVIRONMENT";

export const GET_ORGANIZATION_CALENDAR = "GET_ORGANIZATION_CALENDAR";
export const SET_ORGANIZATION_CALENDAR = "SET_ORGANIZATION_CALENDAR";
export const CALENDAR_SYNCHRONIZATION = "CALENDAR_SYNCHRONIZATION";
export const DELETE_CALENDAR_SYNCHRONIZATION = "DELETE_CALENDAR_SYNCHRONIZATION";

export const GET_EXPENSES_DAILY_BREAKDOWN = "GET_EXPENSES_DAILY_BREAKDOWN";
export const SET_EXPENSES_DAILY_BREAKDOWN = "SET_EXPENSES_DAILY_BREAKDOWN";

export const GET_ORGANIZATION_LIMIT_HITS = "GET_ORGANIZATION_LIMIT_HITS";
export const SET_ORGANIZATION_LIMIT_HITS = "SET_ORGANIZATION_LIMIT_HITS";

export const GET_GLOBAL_POOL_POLICIES = "GET_GLOBAL_POOL_POLICIES";
export const SET_GLOBAL_POOL_POLICIES = "SET_GLOBAL_POOL_POLICIES";

export const GET_GLOBAL_RESOURCE_CONSTRAINTS = "GET_GLOBAL_RESOURCE_CONSTRAINTS";
export const SET_GLOBAL_RESOURCE_CONSTRAINTS = "SET_GLOBAL_RESOURCE_CONSTRAINTS";

export const GET_ARCHIVED_OPTIMIZATIONS_COUNT = "GET_ARCHIVED_OPTIMIZATIONS_COUNT";
export const SET_ARCHIVED_OPTIMIZATIONS_COUNT = "SET_ARCHIVED_OPTIMIZATIONS_COUNT";

export const GET_ARCHIVED_OPTIMIZATIONS_BREAKDOWN = "GET_ARCHIVED_OPTIMIZATIONS_BREAKDOWN";
export const SET_ARCHIVED_OPTIMIZATIONS_BREAKDOWN = "SET_ARCHIVED_OPTIMIZATIONS_BREAKDOWN";

export const GET_ARCHIVED_OPTIMIZATION_DETAILS = "GET_ARCHIVED_OPTIMIZATION_DETAILS";
export const SET_ARCHIVED_OPTIMIZATION_DETAILS = "SET_ARCHIVED_OPTIMIZATION_DETAILS";

export const GET_ML_MODELS = "GET_ML_MODELS";
export const SET_ML_MODELS = "SET_ML_MODELS";

export const GET_ML_MODEL = "GET_ML_MODEL";
export const SET_ML_MODEL = "SET_ML_MODEL";
export const CREATE_ML_MODEL = "CREATE_ML_MODEL";
export const UPDATE_ML_MODEL = "UPDATE_ML_MODEL";
export const DELETE_ML_MODEL = "DELETE_ML_MODEL";

export const GET_ML_MODEL_RECOMMENDATIONS = "GET_ML_MODEL_RECOMMENDATIONS";
export const SET_ML_MODEL_RECOMMENDATIONS = "SET_ML_MODEL_RECOMMENDATIONS";

export const GET_ML_MODEL_RUNS = "GET_ML_MODEL_RUNS";
export const SET_ML_MODEL_RUNS = "SET_ML_MODEL_RUNS";

export const GET_ML_RUN_DETAILS = "GET_ML_RUN_DETAILS";
export const SET_ML_RUN_DETAILS = "SET_ML_RUN_DETAILS";

export const GET_ML_RUN_DETAILS_BREAKDOWN = "GET_ML_RUN_DETAILS_BREAKDOWN";
export const SET_ML_RUN_DETAILS_BREAKDOWN = "SET_ML_RUN_DETAILS_BREAKDOWN";

export const GET_ML_GLOBAL_PARAMETERS = "GET_ML_GLOBAL_PARAMETERS";
export const SET_ML_GLOBAL_PARAMETERS = "SET_ML_GLOBAL_PARAMETERS";

export const CREATE_GLOBAL_PARAMETER = "CREATE_GLOBAL_PARAMETER";
export const UPDATE_GLOBAL_PARAMETER = "UPDATE_GLOBAL_PARAMETER";
export const DELETE_GLOBAL_PARAMETER = "DELETE_GLOBAL_PARAMETER";

export const GET_ML_GLOBAL_PARAMETER = "GET_ML_GLOBAL_PARAMETER";
export const SET_ML_GLOBAL_PARAMETER = "SET_ML_GLOBAL_PARAMETER";

export const GET_PROFILING_TOKEN = "GET_PROFILING_TOKEN";
export const SET_PROFILING_TOKEN = "SET_PROFILING_TOKEN";

export const GET_ML_EXECUTORS = "GET_ML_EXECUTORS";
export const SET_ML_EXECUTORS = "SET_ML_EXECUTORS";
export const GET_ML_EXECUTORS_BREAKDOWN = "GET_ML_EXECUTORS_BREAKDOWN";
export const SET_ML_EXECUTORS_BREAKDOWN = "SET_ML_EXECUTORS_BREAKDOWN";

export const GET_RI_SP_USAGE_BREAKDOWN = "GET_RI_SP_USAGE_BREAKDOWN";
export const SET_RI_SP_USAGE_BREAKDOWN = "SET_RI_SP_USAGE_BREAKDOWN";
export const GET_RI_SP_EXPENSES_BREAKDOWN = "GET_RI_SP_EXPENSES_BREAKDOWN";
export const SET_RI_SP_EXPENSES_BREAKDOWN = "SET_RI_SP_EXPENSES_BREAKDOWN";

export const GET_ML_RUNSET_TEMPLATES = "GET_ML_RUNSET_TEMPLATES";
export const SET_ML_RUNSET_TEMPLATES = "SET_ML_RUNSET_TEMPLATES";

export const GET_ML_RUNSET_TEMPLATE = "GET_ML_RUNSET_TEMPLATE";
export const SET_ML_RUNSET_TEMPLATE = "SET_ML_RUNSET_TEMPLATE";
export const CREATE_ML_RUNSET_TEMPLATE = "CREATE_ML_RUNSET_TEMPLATE";
export const UPDATE_ML_RUNSET_TEMPLATE = "UPDATE_ML_RUNSET_TEMPLATE";
export const DELETE_ML_RUNSET_TEMPLATE = "DELETE_ML_RUNSET_TEMPLATE";

export const GET_ML_RUNSETS = "GET_ML_RUNSETS";
export const SET_ML_RUNSETS = "SET_ML_RUNSETS";

export const GET_ML_RUNSETS_RUNS = "GET_ML_RUNSETS_RUNS";
export const SET_ML_RUNSETS_RUNS = "SET_ML_RUNSETS_RUNS";

export const GET_ML_RUNSET = "GET_ML_RUNSET";
export const SET_ML_RUNSET = "SET_ML_RUNSET";

export const CREATE_ML_RUNSET = "CREATE_ML_RUNSET";
export const STOP_ML_RUNSET = "STOP_ML_RUNSET";

export const GET_ML_RUNSET_EXECUTORS = "GET_ML_RUNSET_EXECUTORS";
export const SET_ML_RUNSET_EXECUTORS = "SET_ML_RUNSET_EXECUTORS";

export const GET_ORGANIZATION_BI_EXPORT = "GET_ORGANIZATION_BI_EXPORT";
export const SET_ORGANIZATION_BI_EXPORTS = "SET_ORGANIZATION_BI_EXPORTS";
export const CREATE_ORGANIZATION_BI_EXPORT = "CREATE_ORGANIZATION_BI_EXPORT";
export const GET_BI_EXPORT = "GET_BI_EXPORT";
export const SET_BI_EXPORT = "SET_BI_EXPORT";
export const UPDATE_BI_EXPORT = "UPDATE_BI_EXPORT";
export const DELETE_BI_EXPORT = "DELETE_BI_EXPORT";

export const GET_RELEVANT_FLAVORS = "GET_RELEVANT_FLAVORS";
export const SET_RELEVANT_FLAVORS = "SET_RELEVANT_FLAVORS";

export const GET_S3_DUPLICATES_ORGANIZATION_SETTINGS = "GET_S3_DUPLICATES_ORGANIZATION_SETTINGS";
export const SET_S3_DUPLICATES_ORGANIZATION_SETTINGS = "SET_S3_DUPLICATES_ORGANIZATION_SETTINGS";
export const UPDATE_S3_DUPLICATES_ORGANIZATION_SETTINGS = "UPDATE_S3_DUPLICATES_ORGANIZATION_SETTINGS";

export const GET_ORGANIZATION_CLOUD_RESOURCES = "GET_ORGANIZATION_CLOUD_RESOURCES";
export const SET_ORGANIZATION_CLOUD_RESOURCES = "SET_ORGANIZATION_CLOUD_RESOURCES";

export const GET_ORGANIZATION_GEMINIS = "GET_ORGANIZATION_GEMINIS";
export const SET_ORGANIZATION_GEMINIS = "SET_ORGANIZATION_GEMINIS";
export const CREATE_ORGANIZATION_GEMINI = "CREATE_ORGANIZATION_GEMINI";
export const GET_GEMINI = "GET_GEMINI";
export const SET_GEMINI = "SET_GEMINI";

export const CREATE_SURVEY = "CREATE_SURVEY";

export const GET_POWER_SCHEDULES = "GET_POWER_SCHEDULES";
export const SET_POWER_SCHEDULES = "SET_POWER_SCHEDULES";
export const GET_POWER_SCHEDULE = "GET_POWER_SCHEDULE";
export const SET_POWER_SCHEDULE = "SET_POWER_SCHEDULE";
export const DELETE_POWER_SCHEDULE = "DELETE_POWER_SCHEDULE";
export const UPDATE_POWER_SCHEDULE = "UPDATE_POWER_SCHEDULE";
export const ATTACH_INSTANCES_TO_SCHEDULE = "ATTACH_INSTANCES_TO_SCHEDULE";
export const REMOVE_INSTANCES_FROM_SCHEDULE = "REMOVE_INSTANCES_FROM_SCHEDULE";
export const CREATE_POWER_SCHEDULES = "CREATE_POWER_SCHEDULES";
