ARG BUILDTAG=build
ARG IMAGE=
FROM ${IMAGE}:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

COPY docker_images/test-requirements.txt docker_images/.pylintrc ./
RUN pip install --no-cache-dir -r test-requirements.txt
