""""initial"

Revision ID: 86a61e321f5a
Revises:
Create Date: 2018-03-16 13:54:46.464948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000000000001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
                    sa.Column('created_at', sa.Integer(), nullable=False),
                    sa.Column('deleted_at', sa.Integer(), nullable=False),
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('user_id', sa.String(length=36), nullable=False),
                    sa.Column('event_object_type', sa.String(length=64),
                              nullable=True),
                    sa.Column('event_object_id', sa.String(length=36),
                              nullable=True),
                    sa.Column('event_class', sa.String(length=32),
                              nullable=True),
                    sa.Column('event_level', sa.String(length=64),
                              nullable=True),
                    sa.Column('event_ack', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('reaction',
                    sa.Column('created_at', sa.Integer(), nullable=False),
                    sa.Column('deleted_at', sa.Integer(), nullable=False),
                    sa.Column('id', sa.String(length=36), nullable=False),
                    sa.Column('notification_id', sa.String(length=36),
                              nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=True),
                    sa.Column('type', sa.Enum(
                        'EMAIL', 'SMS', 'HTTP_CALLBACK', name='reactiontype'),
                              nullable=False),
                    sa.Column('payload', sa.TEXT(), nullable=True),
                    sa.ForeignKeyConstraint(['notification_id'],
                                            ['notification.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction')
    op.drop_table('notification')
    # ### end Alembic commands ###
