export const CREATE_USER = "CREATE_USER";

export const GET_TOKEN = "GET_TOKEN";
export const SET_TOKEN = "SET_TOKEN";

export const GET_USER = "GET_USER";
export const SET_USER = "SET_USER";

export const GET_ORGANIZATION_ALLOWED_ACTIONS = "GET_ORGANIZATION_ALLOWED_ACTIONS";
export const GET_POOL_ALLOWED_ACTIONS = "GET_POOL_ALLOWED_ACTIONS";
export const GET_RESOURCE_ALLOWED_ACTIONS = "GET_RESOURCE_ALLOWED_ACTIONS";
export const SET_ALLOWED_ACTIONS = "SET_ALLOWED_ACTIONS";

export const RESET_PASSWORD = "RESET_PASSWORD";

export const SIGN_IN = "SIGN_IN";
