ARG BUILDTAG=build
FROM katara_worker:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

WORKDIR /usr/src/app/


COPY katara/katara_worker/test-requirements.txt katara/test-requirements.txt
COPY katara/.pylintrc katara/.coveragerc ./katara/katara_worker/

RUN pip install --no-cache-dir -r katara/test-requirements.txt
