export const UPDATE_USER_ASSIGNMENT = "UPDATE_USER_ASSIGNMENT";

export const GET_JIRA_ORGANIZATION_STATUS = "GET_JIRA_ORGANIZATION_STATUS";
export const SET_JIRA_ORGANIZATION_STATUS = "SET_JIRA_ORGANIZATION_STATUS";
