ARG BUILDTAG=build
FROM gemini_scheduler:${BUILDTAG}

WORKDIR /usr/src/app/

COPY gemini/gemini_scheduler/test-requirements.txt gemini/gemini_scheduler/test-requirements.txt
COPY gemini/.pylintrc gemini/.coveragerc ./gemini/gemini_scheduler/

RUN pip install --no-cache-dir -r gemini/gemini_scheduler/test-requirements.txt
