ARG BUILDTAG=build
FROM gemini_scheduler:${BUILDTAG}

WORKDIR /usr/src/app/

COPY gemini/gemini_scheduler/test-requirements.txt ./test-requirements.txt
COPY gemini/.pylintrc gemini/.coveragerc ./

RUN pip install --no-cache-dir -r test-requirements.txt
