ARG BUILDTAG=build
FROM jira_ui:${BUILDTAG}

# installing only dev dependencies for ui prettier and linter check
WORKDIR "/usr/src/app/ui"
USER root

RUN mv .disabled.eslintrc.json .eslintrc.json 
RUN npm ci --ignore-scripts -D