ARG BUILDTAG=build
FROM pharos_receiver:${BUILDTAG}
LABEL org.opencontainers.image.authors="Hystax"

WORKDIR /usr/src/app/

COPY pharos_backend/pharos_receiver/test-requirements.txt ./pharos_backend/

COPY pharos_backend/.pylintrc pharos_backend/.noserc pharos_backend/.coveragerc ./pharos_backend/pharos_receiver/
RUN pip install --no-cache-dir -r ./pharos_backend/test-requirements.txt
