FROM optscale_python:local
MAINTAINER Hystax

WORKDIR /usr/src/app/katara_worker
ENV PYTHONPATH=/usr/src/app/

COPY requirements_worker.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY katara_worker/reports_generators ./reports_generators
COPY katara_worker/*.py ./

CMD ["python", "-u","/usr/src/app/katara_worker/main.py"]
