ARG BUILDTAG=build
FROM herald:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY herald_server/tests/ ./tests
