export const CONNECT_SLACK_USER = "CONNECT_SLACK_USER";

export const GET_SLACK_INSTALLATION_PATH = "GET_SLACK_INSTALLATION_PATH";
export const SET_SLACK_INSTALLATION_PATH = "SET_SLACK_INSTALLATION_PATH";
