ARG BUILDTAG=build
FROM insider_api:${BUILDTAG}
MAINTAINER Hystax

COPY test-requirements.txt .pylintrc .noserc .coveragerc ./
RUN pip install --no-cache-dir -r test-requirements.txt
COPY insider_api/tests ./tests
