import insider.insider_api.handlers.v2.base
import insider.insider_api.handlers.v2.swagger
import insider.insider_api.handlers.v2.region_price_sums
import insider.insider_api.handlers.v2.similar_pricings
import insider.insider_api.handlers.v2.flavors
import insider.insider_api.handlers.v2.flavor_prices
import insider.insider_api.handlers.v2.instances
import insider.insider_api.handlers.v2.flavors_generation
import insider.insider_api.handlers.v2.relevant_flavors
