name: Test and Generate Coverage Report

on:
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
      continue-on-error: true
 
    - name: Generate coverage report
      run: |
         mkdir -p coverage
         coverage xml -o coverage/coverage.xml
      continue-on-error: true

    - name: Commit and push coverage report
      run: |
        git config --global user.name 'saisahoo01'
        git config --global user.email 'sailokeshbasava123@gmail.com'
        git add coverage/coverage.xml
        git commit -m 'Add coverage report'
        git push origin integration
      continue-on-error: true
      env:
        GITHUB_TOKEN: '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'
