name: Test and Generate Coverage Report

on:
  workflow_dispatch:

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage

    - name: Run tests with coverage
      run: |
        coverage run -m pytest
      continue-on-error: true
 
    - name: Generate coverage report
      run: |
        coverage xml -o auth/coverage.xml
      continue-on-error: true

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: auth/coverage.xml
