name: Coverage Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Python tests and coverage
      run: |
        coverage run -m pytest
        coverage xml
        cp -r coverage.xml auth/

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: public/
