name: Label UI for NGUI changes

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Filter changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            ngui:
              - 'ngui/**'

      - name: Add "ui" label if ngui files changed
        if: steps.filter.outputs.ngui == 'true'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ui
