name: Build Arcee test image
run-name: Build arcee test image - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'arcee/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: bash -x build.sh arcee build
