name: Unitests CI for Auth  

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      ImageTag: ${{ steps.ImageTag.outputs.Tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: heeddata/heeddata_mvp
          token: ${{ secrets.GH_TOKEN_ADMIN }}
          ref: develop

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: sailokeshbasava
          password: sailokeshbasava

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push auth
      uses: docker/build-push-action@v4
      with:
          context: .
          file: auth/Dockerfile
          push: true
          tags: sailokeshbasava/new:unitests
          
    - name: Build test image and run tests
      run: bash -x auth/run_test.sh
  
